package edu.hp.model.vo.query.conf.common;

import java.sql.Timestamp;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 27 19:11:52 CST 2013
// ---------------------------------------------------------------------
public interface ConfRmConflictView extends ViewObject {
    Boolean ifConflict(Timestamp actStartTime, Timestamp actEndTime, String clsRmId, String actId);
}
