package edu.hp.model.vo.query.helpdesk;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 15 15:42:45 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpWithEmptyImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpWithEmptyImpl() {
    }

    /**
     * Returns the variable value for cId.
     * @return variable value for cId
     */
    public String getcId() {
        return (String)ensureVariableManager().getVariableValue("cId");
    }

    /**
     * Sets <code>value</code> for variable cId.
     * @param value value to bind as cId
     */
    public void setcId(String value) {
        ensureVariableManager().setVariableValue("cId", value);
    }
}
