package edu.hp.model.vo.query.classrm;

import edu.hp.model.common.BaseView;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 18 22:13:56 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClassroomQueryImpl extends BaseView {
    /**
     * This is the default constructor (do not remove).
     */
    public ClassroomQueryImpl() {
       
    }

    /**
     * Returns the variable value for clsRmNos.
     * @return variable value for clsRmNos
     */
    public String getclsRmNos() {
        return (String)ensureVariableManager().getVariableValue("clsRmNos");
    }

    /**
     * Sets <code>value</code> for variable clsRmNos.
     * @param value value to bind as clsRmNos
     */
    public void setclsRmNos(String value) {
        ensureVariableManager().setVariableValue("clsRmNos", value);
    }
}
