package edu.hp.model.vo.query.vehicle.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 01 13:35:08 CST 2013
// ---------------------------------------------------------------------
public interface VehicleUsuageByDay extends ViewObject {
    void setday(String value);

    void doQuery(String day);
}
