package edu.hp.model.vo.query.vehicle.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 31 13:06:51 CST 2013
// ---------------------------------------------------------------------
public interface VehicleCalQueryView extends ViewObject {
    void findByUserId(boolean enabled, String userId);

    void refreshCalendar(String vehicleIds);
}
