package com.xy.scpms.model.vo;

import com.xy.scpms.model.utils.Codes;


import com.xy.scpms.model.vo.common.InvoiceRequisitionView;

import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 21:42:28 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceRequisitionViewImpl extends ViewObjectImpl implements InvoiceRequisitionView {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceRequisitionViewImpl() {
    }

    public boolean isAlreadyApplied(Number paymentId) {

        boolean result = false;

        this.setApplyViewCriteriaNames(null);
        ViewCriteria criteria = this.getViewCriteria("isApplied");
        this.applyViewCriteria(criteria);
        this.setpaymentId(paymentId);
        this.executeQuery();
        Row[] rows = this.getAllRowsInRange();
        if (rows != null && rows.length > 0)
            result = true;

        return result;


    }

    public void setReqApproved(Number id) {
        //根据id查询
        Row[] rows = findByKey(new Key(new Object[] { id }), 1);
        if (rows != null && rows.length > 0) {
            InvoiceRequisitionViewRowImpl row =
                (InvoiceRequisitionViewRowImpl)rows[0];
            Row payment = row.getContractLinePaymentsView();
            payment.setAttribute("Status",
                                 Codes.COL_VALUE_PAYMENT_STATUS_APPROVED);
            row.setAttribute("Status",
                             Codes.COL_VALUE_PAYMENT_STATUS_APPROVED);
        }

    }

    public void setReqRejected(Number id) {
        //根据id查询
        Row[] rows = findByKey(new Key(new Object[] { id }), 1);
        if (rows != null && rows.length > 0) {
            InvoiceRequisitionViewRowImpl row =
                (InvoiceRequisitionViewRowImpl)rows[0];
            Row payment = row.getContractLinePaymentsView();
            payment.setAttribute("Status",
                                 Codes.COL_VALUE_PAYMENT_STATUS_INITIAL);
            row.setAttribute("Status",
                             Codes.COL_VALUE_PAYMENT_STATUS_REJECTED);
        }
    }

    /**
     * Returns the variable value for contractId.
     * @return variable value for contractId
     */
    public Number getpaymentId() {
        return (Number)ensureVariableManager().getVariableValue("paymentId");
    }

    /**
     * Sets <code>value</code> for variable contractId.
     * @param value value to bind as contractId
     */
    public void setpaymentId(Number value) {
        ensureVariableManager().setVariableValue("paymentId", value);
    }

    /**
     * Returns the variable value for dept.
     * @return variable value for dept
     */
    public String getdept() {
        return (String)ensureVariableManager().getVariableValue("dept");
    }

    /**
     * Sets <code>value</code> for variable dept.
     * @param value value to bind as dept
     */
    public void setdept(String value) {
        ensureVariableManager().setVariableValue("dept", value);
    }

    /**
     * Returns the variable value for userName.
     * @return variable value for userName
     */
    public String getuserName() {
        return (String)ensureVariableManager().getVariableValue("userName");
    }

    /**
     * Sets <code>value</code> for variable userName.
     * @param value value to bind as userName
     */
    public void setuserName(String value) {
        ensureVariableManager().setVariableValue("userName", value);
    }
}
