package com.xy.scpms.model.vo;

import com.xy.scpms.model.eo.ContractImpl;
import com.xy.scpms.model.eo.ContractLineImpl;
import com.xy.scpms.model.eo.ContractLinePaymentsImpl;
import com.xy.scpms.model.eo.InvoiceRequisitionImpl;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 21:42:27 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceRequisitionViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_INVOICEREQUISITION = 0;
    public static final int ENTITY_USERS = 1;
    public static final int ENTITY_CONTRACT = 2;
    public static final int ENTITY_CONTRACTLINE = 3;
    public static final int ENTITY_CONTRACTLINEPAYMENTS = 4;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getId();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setId((Number)value);
            }
        }
        ,
        Requestor {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getRequestor();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setRequestor((String)value);
            }
        }
        ,
        RequestDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getRequestDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setRequestDate((Date)value);
            }
        }
        ,
        LinePaymentId {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getLinePaymentId();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setLinePaymentId((Number)value);
            }
        }
        ,
        Amount {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getAmount();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setAmount((Number)value);
            }
        }
        ,
        Status {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Memo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMemo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMemo((String)value);
            }
        }
        ,
        DeptHeadApprover {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getDeptHeadApprover();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setDeptHeadApprover((String)value);
            }
        }
        ,
        DeptHeadOutcome {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getDeptHeadOutcome();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setDeptHeadOutcome((String)value);
            }
        }
        ,
        DeptHeadDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getDeptHeadDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setDeptHeadDate((Date)value);
            }
        }
        ,
        DeptHeadMemo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getDeptHeadMemo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setDeptHeadMemo((String)value);
            }
        }
        ,
        MrktHeadApprover {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMrktHeadApprover();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMrktHeadApprover((String)value);
            }
        }
        ,
        MrktHeadOutcome {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMrktHeadOutcome();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMrktHeadOutcome((String)value);
            }
        }
        ,
        MrktHeadMemo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMrktHeadMemo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMrktHeadMemo((String)value);
            }
        }
        ,
        MrktHeadDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMrktHeadDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMrktHeadDate((Date)value);
            }
        }
        ,
        BatchId {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getBatchId();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setBatchId((Number)value);
            }
        }
        ,
        Deleted {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getDeleted();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setDeleted((String)value);
            }
        }
        ,
        ContractId {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getContractId();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setContractId((Number)value);
            }
        }
        ,
        Department {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getDepartment();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        FullName {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getFullName();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setFullName((String)value);
            }
        }
        ,
        Username {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getUsername();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setUsername((String)value);
            }
        }
        ,
        Owner {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getOwner();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setOwner((String)value);
            }
        }
        ,
        Plant {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getPlant();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setPlant((String)value);
            }
        }
        ,
        Broker {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getBroker();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setBroker((String)value);
            }
        }
        ,
        Contact {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getContact();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setContact((String)value);
            }
        }
        ,
        AuthName {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getAuthName();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setAuthName((String)value);
            }
        }
        ,
        LineId {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getLineId();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        MnftShipNo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMnftShipNo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMnftShipNo((String)value);
            }
        }
        ,
        AuthName1 {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getAuthName1();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setAuthName1((String)value);
            }
        }
        ,
        AuthType {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getAuthType();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setAuthType((String)value);
            }
        }
        ,
        ContractEntity {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getContractEntity();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setContractEntity((String)value);
            }
        }
        ,
        ContractType {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getContractType();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setContractType((String)value);
            }
        }
        ,
        ContractNo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getContractNo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setContractNo((String)value);
            }
        }
        ,
        AuthorizerType {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getAuthorizerType();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setAuthorizerType((String)value);
            }
        }
        ,
        CustomerContactName {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getCustomerContactName();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setCustomerContactName((String)value);
            }
        }
        ,
        FirstDesignFee {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getFirstDesignFee();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setFirstDesignFee((Number)value);
            }
        }
        ,
        ProjectManager {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getProjectManager();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setProjectManager((String)value);
            }
        }
        ,
        RegionManager {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getRegionManager();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setRegionManager((String)value);
            }
        }
        ,
        ProjectName {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getProjectName();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setProjectName((String)value);
            }
        }
        ,
        ShipModel {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipModel();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipModel((String)value);
            }
        }
        ,
        ShipNoInternal {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipNoInternal();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipNoInternal((String)value);
            }
        }
        ,
        IdofContract {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getIdofContract();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setIdofContract((Number)value);
            }
        }
        ,
        TotalAmount {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getTotalAmount();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setTotalAmount((Number)value);
            }
        }
        ,
        ShipBroker {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipBroker();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipBroker((String)value);
            }
        }
        ,
        FgCompletionDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getFgCompletionDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setFgCompletionDate((Date)value);
            }
        }
        ,
        WorkStartDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getWorkStartDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setWorkStartDate((Date)value);
            }
        }
        ,
        ShipPrice {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipPrice();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipPrice((Number)value);
            }
        }
        ,
        ShipPlant {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipPlant();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipPlant((String)value);
            }
        }
        ,
        EffectiveDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getEffectiveDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setEffectiveDate((Date)value);
            }
        }
        ,
        ShipClsfctSociety {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipClsfctSociety();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipClsfctSociety((String)value);
            }
        }
        ,
        ImoNo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getImoNo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setImoNo((String)value);
            }
        }
        ,
        Price {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getPrice();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setPrice((Number)value);
            }
        }
        ,
        ContractType1 {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getContractType1();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setContractType1((String)value);
            }
        }
        ,
        Status1 {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getStatus1();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setStatus1((String)value);
            }
        }
        ,
        ShipNoInternal1 {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipNoInternal1();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipNoInternal1((String)value);
            }
        }
        ,
        LineNo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getLineNo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setLineNo((Number)value);
            }
        }
        ,
        ShipName {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipName();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipName((String)value);
            }
        }
        ,
        SignOffDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getSignOffDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setSignOffDate((Date)value);
            }
        }
        ,
        Memo1 {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMemo1();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMemo1((String)value);
            }
        }
        ,
        OwnerType {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getOwnerType();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setOwnerType((String)value);
            }
        }
        ,
        BrokerType {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getBrokerType();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setBrokerType((String)value);
            }
        }
        ,
        PlantType {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getPlantType();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setPlantType((String)value);
            }
        }
        ,
        Currency {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getCurrency();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        ShipMnftNo {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipMnftNo();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipMnftNo((String)value);
            }
        }
        ,
        ExchangeRate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getExchangeRate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setExchangeRate((Number)value);
            }
        }
        ,
        ShipOwner {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getShipOwner();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setShipOwner((String)value);
            }
        }
        ,
        IdofLine {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getIdofLine();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setIdofLine((Number)value);
            }
        }
        ,
        PaymentName {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getPaymentName();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setPaymentName((String)value);
            }
        }
        ,
        PaymentPlanDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getPaymentPlanDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setPaymentPlanDate((Date)value);
            }
        }
        ,
        PaymentPlanAmount {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getPaymentPlanAmount();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setPaymentPlanAmount((Number)value);
            }
        }
        ,
        PaymentPlanInvoiceDate {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getPaymentPlanInvoiceDate();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setPaymentPlanInvoiceDate((Date)value);
            }
        }
        ,
        Memo2 {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getMemo2();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setMemo2((String)value);
            }
        }
        ,
        Id1 {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getId1();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setId1((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setCustomerId((String)value);
            }
        }
        ,
        CustomerContactor {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getCustomerContactor();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setCustomerContactor((String)value);
            }
        }
        ,
        ContractLinePaymentsView {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getContractLinePaymentsView();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LinePaymentDetailView {
            public Object get(InvoiceRequisitionViewRowImpl obj) {
                return obj.getLinePaymentDetailView();
            }

            public void put(InvoiceRequisitionViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(InvoiceRequisitionViewRowImpl object);

        public abstract void put(InvoiceRequisitionViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int REQUESTOR = AttributesEnum.Requestor.index();
    public static final int REQUESTDATE = AttributesEnum.RequestDate.index();
    public static final int LINEPAYMENTID = AttributesEnum.LinePaymentId.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int MEMO = AttributesEnum.Memo.index();
    public static final int DEPTHEADAPPROVER = AttributesEnum.DeptHeadApprover.index();
    public static final int DEPTHEADOUTCOME = AttributesEnum.DeptHeadOutcome.index();
    public static final int DEPTHEADDATE = AttributesEnum.DeptHeadDate.index();
    public static final int DEPTHEADMEMO = AttributesEnum.DeptHeadMemo.index();
    public static final int MRKTHEADAPPROVER = AttributesEnum.MrktHeadApprover.index();
    public static final int MRKTHEADOUTCOME = AttributesEnum.MrktHeadOutcome.index();
    public static final int MRKTHEADMEMO = AttributesEnum.MrktHeadMemo.index();
    public static final int MRKTHEADDATE = AttributesEnum.MrktHeadDate.index();
    public static final int BATCHID = AttributesEnum.BatchId.index();
    public static final int DELETED = AttributesEnum.Deleted.index();
    public static final int CONTRACTID = AttributesEnum.ContractId.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int FULLNAME = AttributesEnum.FullName.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int OWNER = AttributesEnum.Owner.index();
    public static final int PLANT = AttributesEnum.Plant.index();
    public static final int BROKER = AttributesEnum.Broker.index();
    public static final int CONTACT = AttributesEnum.Contact.index();
    public static final int AUTHNAME = AttributesEnum.AuthName.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int MNFTSHIPNO = AttributesEnum.MnftShipNo.index();
    public static final int AUTHNAME1 = AttributesEnum.AuthName1.index();
    public static final int AUTHTYPE = AttributesEnum.AuthType.index();
    public static final int CONTRACTENTITY = AttributesEnum.ContractEntity.index();
    public static final int CONTRACTTYPE = AttributesEnum.ContractType.index();
    public static final int CONTRACTNO = AttributesEnum.ContractNo.index();
    public static final int AUTHORIZERTYPE = AttributesEnum.AuthorizerType.index();
    public static final int CUSTOMERCONTACTNAME = AttributesEnum.CustomerContactName.index();
    public static final int FIRSTDESIGNFEE = AttributesEnum.FirstDesignFee.index();
    public static final int PROJECTMANAGER = AttributesEnum.ProjectManager.index();
    public static final int REGIONMANAGER = AttributesEnum.RegionManager.index();
    public static final int PROJECTNAME = AttributesEnum.ProjectName.index();
    public static final int SHIPMODEL = AttributesEnum.ShipModel.index();
    public static final int SHIPNOINTERNAL = AttributesEnum.ShipNoInternal.index();
    public static final int IDOFCONTRACT = AttributesEnum.IdofContract.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int SHIPBROKER = AttributesEnum.ShipBroker.index();
    public static final int FGCOMPLETIONDATE = AttributesEnum.FgCompletionDate.index();
    public static final int WORKSTARTDATE = AttributesEnum.WorkStartDate.index();
    public static final int SHIPPRICE = AttributesEnum.ShipPrice.index();
    public static final int SHIPPLANT = AttributesEnum.ShipPlant.index();
    public static final int EFFECTIVEDATE = AttributesEnum.EffectiveDate.index();
    public static final int SHIPCLSFCTSOCIETY = AttributesEnum.ShipClsfctSociety.index();
    public static final int IMONO = AttributesEnum.ImoNo.index();
    public static final int PRICE = AttributesEnum.Price.index();
    public static final int CONTRACTTYPE1 = AttributesEnum.ContractType1.index();
    public static final int STATUS1 = AttributesEnum.Status1.index();
    public static final int SHIPNOINTERNAL1 = AttributesEnum.ShipNoInternal1.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int SHIPNAME = AttributesEnum.ShipName.index();
    public static final int SIGNOFFDATE = AttributesEnum.SignOffDate.index();
    public static final int MEMO1 = AttributesEnum.Memo1.index();
    public static final int OWNERTYPE = AttributesEnum.OwnerType.index();
    public static final int BROKERTYPE = AttributesEnum.BrokerType.index();
    public static final int PLANTTYPE = AttributesEnum.PlantType.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int SHIPMNFTNO = AttributesEnum.ShipMnftNo.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int SHIPOWNER = AttributesEnum.ShipOwner.index();
    public static final int IDOFLINE = AttributesEnum.IdofLine.index();
    public static final int PAYMENTNAME = AttributesEnum.PaymentName.index();
    public static final int PAYMENTPLANDATE = AttributesEnum.PaymentPlanDate.index();
    public static final int PAYMENTPLANAMOUNT = AttributesEnum.PaymentPlanAmount.index();
    public static final int PAYMENTPLANINVOICEDATE = AttributesEnum.PaymentPlanInvoiceDate.index();
    public static final int MEMO2 = AttributesEnum.Memo2.index();
    public static final int ID1 = AttributesEnum.Id1.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int CUSTOMERCONTACTOR = AttributesEnum.CustomerContactor.index();
    public static final int CONTRACTLINEPAYMENTSVIEW = AttributesEnum.ContractLinePaymentsView.index();
    public static final int LINEPAYMENTDETAILVIEW = AttributesEnum.LinePaymentDetailView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceRequisitionViewRowImpl() {
    }

    /**
     * Gets InvoiceRequisition entity object.
     * @return the InvoiceRequisition
     */
    public InvoiceRequisitionImpl getInvoiceRequisition() {
        return (InvoiceRequisitionImpl)getEntity(ENTITY_INVOICEREQUISITION);
    }

    /**
     * Gets Users entity object.
     * @return the Users
     */
    public EntityImpl getUsers() {
        return (EntityImpl)getEntity(ENTITY_USERS);
    }

    /**
     * Gets Contract entity object.
     * @return the Contract
     */
    public ContractImpl getContract() {
        return (ContractImpl)getEntity(ENTITY_CONTRACT);
    }

    /**
     * Gets ContractLine entity object.
     * @return the ContractLine
     */
    public ContractLineImpl getContractLine() {
        return (ContractLineImpl)getEntity(ENTITY_CONTRACTLINE);
    }

    /**
     * Gets ContractLinePayments entity object.
     * @return the ContractLinePayments
     */
    public ContractLinePaymentsImpl getContractLinePayments() {
        return (ContractLinePaymentsImpl)getEntity(ENTITY_CONTRACTLINEPAYMENTS);
    }

    /**
     * Gets the attribute value for ID using the alias name Id.
     * @return the ID
     */
    public Number getId() {
        return (Number) getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id.
     * @param value value to set the ID
     */
    public void setId(Number value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for REQUESTOR using the alias name Requestor.
     * @return the REQUESTOR
     */
    public String getRequestor() {
        return (String) getAttributeInternal(REQUESTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUESTOR using the alias name Requestor.
     * @param value value to set the REQUESTOR
     */
    public void setRequestor(String value) {
        setAttributeInternal(REQUESTOR, value);
    }

    /**
     * Gets the attribute value for REQUEST_DATE using the alias name RequestDate.
     * @return the REQUEST_DATE
     */
    public Date getRequestDate() {
        return (Date) getAttributeInternal(REQUESTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUEST_DATE using the alias name RequestDate.
     * @param value value to set the REQUEST_DATE
     */
    public void setRequestDate(Date value) {
        setAttributeInternal(REQUESTDATE, value);
    }

    /**
     * Gets the attribute value for LINE_PAYMENT_ID using the alias name LinePaymentId.
     * @return the LINE_PAYMENT_ID
     */
    public Number getLinePaymentId() {
        return (Number) getAttributeInternal(LINEPAYMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_PAYMENT_ID using the alias name LinePaymentId.
     * @param value value to set the LINE_PAYMENT_ID
     */
    public void setLinePaymentId(Number value) {
        setAttributeInternal(LINEPAYMENTID, value);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for MEMO using the alias name Memo.
     * @return the MEMO
     */
    public String getMemo() {
        return (String) getAttributeInternal(MEMO);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMO using the alias name Memo.
     * @param value value to set the MEMO
     */
    public void setMemo(String value) {
        setAttributeInternal(MEMO, value);
    }

    /**
     * Gets the attribute value for DEPT_HEAD_APPROVER using the alias name DeptHeadApprover.
     * @return the DEPT_HEAD_APPROVER
     */
    public String getDeptHeadApprover() {
        return (String) getAttributeInternal(DEPTHEADAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_HEAD_APPROVER using the alias name DeptHeadApprover.
     * @param value value to set the DEPT_HEAD_APPROVER
     */
    public void setDeptHeadApprover(String value) {
        setAttributeInternal(DEPTHEADAPPROVER, value);
    }

    /**
     * Gets the attribute value for DEPT_HEAD_OUTCOME using the alias name DeptHeadOutcome.
     * @return the DEPT_HEAD_OUTCOME
     */
    public String getDeptHeadOutcome() {
        return (String) getAttributeInternal(DEPTHEADOUTCOME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_HEAD_OUTCOME using the alias name DeptHeadOutcome.
     * @param value value to set the DEPT_HEAD_OUTCOME
     */
    public void setDeptHeadOutcome(String value) {
        setAttributeInternal(DEPTHEADOUTCOME, value);
    }

    /**
     * Gets the attribute value for DEPT_HEAD_DATE using the alias name DeptHeadDate.
     * @return the DEPT_HEAD_DATE
     */
    public Date getDeptHeadDate() {
        return (Date) getAttributeInternal(DEPTHEADDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_HEAD_DATE using the alias name DeptHeadDate.
     * @param value value to set the DEPT_HEAD_DATE
     */
    public void setDeptHeadDate(Date value) {
        setAttributeInternal(DEPTHEADDATE, value);
    }

    /**
     * Gets the attribute value for DEPT_HEAD_MEMO using the alias name DeptHeadMemo.
     * @return the DEPT_HEAD_MEMO
     */
    public String getDeptHeadMemo() {
        return (String) getAttributeInternal(DEPTHEADMEMO);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_HEAD_MEMO using the alias name DeptHeadMemo.
     * @param value value to set the DEPT_HEAD_MEMO
     */
    public void setDeptHeadMemo(String value) {
        setAttributeInternal(DEPTHEADMEMO, value);
    }

    /**
     * Gets the attribute value for MRKT_HEAD_APPROVER using the alias name MrktHeadApprover.
     * @return the MRKT_HEAD_APPROVER
     */
    public String getMrktHeadApprover() {
        return (String) getAttributeInternal(MRKTHEADAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for MRKT_HEAD_APPROVER using the alias name MrktHeadApprover.
     * @param value value to set the MRKT_HEAD_APPROVER
     */
    public void setMrktHeadApprover(String value) {
        setAttributeInternal(MRKTHEADAPPROVER, value);
    }

    /**
     * Gets the attribute value for MRKT_HEAD_OUTCOME using the alias name MrktHeadOutcome.
     * @return the MRKT_HEAD_OUTCOME
     */
    public String getMrktHeadOutcome() {
        return (String) getAttributeInternal(MRKTHEADOUTCOME);
    }

    /**
     * Sets <code>value</code> as attribute value for MRKT_HEAD_OUTCOME using the alias name MrktHeadOutcome.
     * @param value value to set the MRKT_HEAD_OUTCOME
     */
    public void setMrktHeadOutcome(String value) {
        setAttributeInternal(MRKTHEADOUTCOME, value);
    }

    /**
     * Gets the attribute value for MRKT_HEAD_MEMO using the alias name MrktHeadMemo.
     * @return the MRKT_HEAD_MEMO
     */
    public String getMrktHeadMemo() {
        return (String) getAttributeInternal(MRKTHEADMEMO);
    }

    /**
     * Sets <code>value</code> as attribute value for MRKT_HEAD_MEMO using the alias name MrktHeadMemo.
     * @param value value to set the MRKT_HEAD_MEMO
     */
    public void setMrktHeadMemo(String value) {
        setAttributeInternal(MRKTHEADMEMO, value);
    }

    /**
     * Gets the attribute value for MRKT_HEAD_DATE using the alias name MrktHeadDate.
     * @return the MRKT_HEAD_DATE
     */
    public Date getMrktHeadDate() {
        return (Date) getAttributeInternal(MRKTHEADDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MRKT_HEAD_DATE using the alias name MrktHeadDate.
     * @param value value to set the MRKT_HEAD_DATE
     */
    public void setMrktHeadDate(Date value) {
        setAttributeInternal(MRKTHEADDATE, value);
    }

    /**
     * Gets the attribute value for BATCH_ID using the alias name BatchId.
     * @return the BATCH_ID
     */
    public Number getBatchId() {
        return (Number) getAttributeInternal(BATCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCH_ID using the alias name BatchId.
     * @param value value to set the BATCH_ID
     */
    public void setBatchId(Number value) {
        setAttributeInternal(BATCHID, value);
    }

    /**
     * Gets the attribute value for DELETED using the alias name Deleted.
     * @return the DELETED
     */
    public String getDeleted() {
        return (String) getAttributeInternal(DELETED);
    }

    /**
     * Sets <code>value</code> as attribute value for DELETED using the alias name Deleted.
     * @param value value to set the DELETED
     */
    public void setDeleted(String value) {
        setAttributeInternal(DELETED, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ID using the alias name ContractId.
     * @return the CONTRACT_ID
     */
    public Number getContractId() {
        return (Number) getAttributeInternal(CONTRACTID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ID using the alias name ContractId.
     * @param value value to set the CONTRACT_ID
     */
    public void setContractId(Number value) {
        setAttributeInternal(CONTRACTID, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT using the alias name Department.
     * @return the DEPARTMENT
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT using the alias name Department.
     * @param value value to set the DEPARTMENT
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for FULL_NAME using the alias name FullName.
     * @return the FULL_NAME
     */
    public String getFullName() {
        return (String) getAttributeInternal(FULLNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FULL_NAME using the alias name FullName.
     * @param value value to set the FULL_NAME
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**
     * Gets the attribute value for USERNAME using the alias name Username.
     * @return the USERNAME
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USERNAME using the alias name Username.
     * @param value value to set the USERNAME
     */
    public void setUsername(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for OWNER using the alias name Owner.
     * @return the OWNER
     */
    public String getOwner() {
        return (String) getAttributeInternal(OWNER);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNER using the alias name Owner.
     * @param value value to set the OWNER
     */
    public void setOwner(String value) {
        setAttributeInternal(OWNER, value);
    }

    /**
     * Gets the attribute value for PLANT using the alias name Plant.
     * @return the PLANT
     */
    public String getPlant() {
        return (String) getAttributeInternal(PLANT);
    }

    /**
     * Sets <code>value</code> as attribute value for PLANT using the alias name Plant.
     * @param value value to set the PLANT
     */
    public void setPlant(String value) {
        setAttributeInternal(PLANT, value);
    }

    /**
     * Gets the attribute value for BROKER using the alias name Broker.
     * @return the BROKER
     */
    public String getBroker() {
        return (String) getAttributeInternal(BROKER);
    }

    /**
     * Sets <code>value</code> as attribute value for BROKER using the alias name Broker.
     * @param value value to set the BROKER
     */
    public void setBroker(String value) {
        setAttributeInternal(BROKER, value);
    }

    /**
     * Gets the attribute value for CONTACT using the alias name Contact.
     * @return the CONTACT
     */
    public String getContact() {
        return (String) getAttributeInternal(CONTACT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT using the alias name Contact.
     * @param value value to set the CONTACT
     */
    public void setContact(String value) {
        setAttributeInternal(CONTACT, value);
    }

    /**
     * Gets the attribute value for AUTH_NAME using the alias name AuthName.
     * @return the AUTH_NAME
     */
    public String getAuthName() {
        return (String) getAttributeInternal(AUTHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTH_NAME using the alias name AuthName.
     * @param value value to set the AUTH_NAME
     */
    public void setAuthName(String value) {
        setAttributeInternal(AUTHNAME, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for MNFT_SHIP_NO using the alias name MnftShipNo.
     * @return the MNFT_SHIP_NO
     */
    public String getMnftShipNo() {
        return (String) getAttributeInternal(MNFTSHIPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for MNFT_SHIP_NO using the alias name MnftShipNo.
     * @param value value to set the MNFT_SHIP_NO
     */
    public void setMnftShipNo(String value) {
        setAttributeInternal(MNFTSHIPNO, value);
    }

    /**
     * Gets the attribute value for AUTH_NAME using the alias name AuthName1.
     * @return the AUTH_NAME
     */
    public String getAuthName1() {
        return (String) getAttributeInternal(AUTHNAME1);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTH_NAME using the alias name AuthName1.
     * @param value value to set the AUTH_NAME
     */
    public void setAuthName1(String value) {
        setAttributeInternal(AUTHNAME1, value);
    }

    /**
     * Gets the attribute value for AUTH_TYPE using the alias name AuthType.
     * @return the AUTH_TYPE
     */
    public String getAuthType() {
        return (String) getAttributeInternal(AUTHTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTH_TYPE using the alias name AuthType.
     * @param value value to set the AUTH_TYPE
     */
    public void setAuthType(String value) {
        setAttributeInternal(AUTHTYPE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_ENTITY using the alias name ContractEntity.
     * @return the CONTRACT_ENTITY
     */
    public String getContractEntity() {
        return (String) getAttributeInternal(CONTRACTENTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_ENTITY using the alias name ContractEntity.
     * @param value value to set the CONTRACT_ENTITY
     */
    public void setContractEntity(String value) {
        setAttributeInternal(CONTRACTENTITY, value);
    }

    /**
     * Gets the attribute value for CONTRACT_TYPE using the alias name ContractType.
     * @return the CONTRACT_TYPE
     */
    public String getContractType() {
        return (String) getAttributeInternal(CONTRACTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_TYPE using the alias name ContractType.
     * @param value value to set the CONTRACT_TYPE
     */
    public void setContractType(String value) {
        setAttributeInternal(CONTRACTTYPE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_NO using the alias name ContractNo.
     * @return the CONTRACT_NO
     */
    public String getContractNo() {
        return (String) getAttributeInternal(CONTRACTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_NO using the alias name ContractNo.
     * @param value value to set the CONTRACT_NO
     */
    public void setContractNo(String value) {
        setAttributeInternal(CONTRACTNO, value);
    }

    /**
     * Gets the attribute value for AUTHORIZER_TYPE using the alias name AuthorizerType.
     * @return the AUTHORIZER_TYPE
     */
    public String getAuthorizerType() {
        return (String) getAttributeInternal(AUTHORIZERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTHORIZER_TYPE using the alias name AuthorizerType.
     * @param value value to set the AUTHORIZER_TYPE
     */
    public void setAuthorizerType(String value) {
        setAttributeInternal(AUTHORIZERTYPE, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_CONTACT_NAME using the alias name CustomerContactName.
     * @return the CUSTOMER_CONTACT_NAME
     */
    public String getCustomerContactName() {
        return (String) getAttributeInternal(CUSTOMERCONTACTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_CONTACT_NAME using the alias name CustomerContactName.
     * @param value value to set the CUSTOMER_CONTACT_NAME
     */
    public void setCustomerContactName(String value) {
        setAttributeInternal(CUSTOMERCONTACTNAME, value);
    }

    /**
     * Gets the attribute value for FIRST_DESIGN_FEE using the alias name FirstDesignFee.
     * @return the FIRST_DESIGN_FEE
     */
    public Number getFirstDesignFee() {
        return (Number) getAttributeInternal(FIRSTDESIGNFEE);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_DESIGN_FEE using the alias name FirstDesignFee.
     * @param value value to set the FIRST_DESIGN_FEE
     */
    public void setFirstDesignFee(Number value) {
        setAttributeInternal(FIRSTDESIGNFEE, value);
    }

    /**
     * Gets the attribute value for PROJECT_MANAGER using the alias name ProjectManager.
     * @return the PROJECT_MANAGER
     */
    public String getProjectManager() {
        return (String) getAttributeInternal(PROJECTMANAGER);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_MANAGER using the alias name ProjectManager.
     * @param value value to set the PROJECT_MANAGER
     */
    public void setProjectManager(String value) {
        setAttributeInternal(PROJECTMANAGER, value);
    }

    /**
     * Gets the attribute value for REGION_MANAGER using the alias name RegionManager.
     * @return the REGION_MANAGER
     */
    public String getRegionManager() {
        return (String) getAttributeInternal(REGIONMANAGER);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_MANAGER using the alias name RegionManager.
     * @param value value to set the REGION_MANAGER
     */
    public void setRegionManager(String value) {
        setAttributeInternal(REGIONMANAGER, value);
    }

    /**
     * Gets the attribute value for PROJECT_NAME using the alias name ProjectName.
     * @return the PROJECT_NAME
     */
    public String getProjectName() {
        return (String) getAttributeInternal(PROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_NAME using the alias name ProjectName.
     * @param value value to set the PROJECT_NAME
     */
    public void setProjectName(String value) {
        setAttributeInternal(PROJECTNAME, value);
    }

    /**
     * Gets the attribute value for SHIP_MODEL using the alias name ShipModel.
     * @return the SHIP_MODEL
     */
    public String getShipModel() {
        return (String) getAttributeInternal(SHIPMODEL);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_MODEL using the alias name ShipModel.
     * @param value value to set the SHIP_MODEL
     */
    public void setShipModel(String value) {
        setAttributeInternal(SHIPMODEL, value);
    }

    /**
     * Gets the attribute value for SHIP_NO_INTERNAL using the alias name ShipNoInternal.
     * @return the SHIP_NO_INTERNAL
     */
    public String getShipNoInternal() {
        return (String) getAttributeInternal(SHIPNOINTERNAL);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_NO_INTERNAL using the alias name ShipNoInternal.
     * @param value value to set the SHIP_NO_INTERNAL
     */
    public void setShipNoInternal(String value) {
        setAttributeInternal(SHIPNOINTERNAL, value);
    }

    /**
     * Gets the attribute value for ID using the alias name IdofContract.
     * @return the ID
     */
    public Number getIdofContract() {
        return (Number) getAttributeInternal(IDOFCONTRACT);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name IdofContract.
     * @param value value to set the ID
     */
    public void setIdofContract(Number value) {
        setAttributeInternal(IDOFCONTRACT, value);
    }

    /**
     * Gets the attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @return the TOTAL_AMOUNT
     */
    public Number getTotalAmount() {
        return (Number) getAttributeInternal(TOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_AMOUNT using the alias name TotalAmount.
     * @param value value to set the TOTAL_AMOUNT
     */
    public void setTotalAmount(Number value) {
        setAttributeInternal(TOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for SHIP_BROKER using the alias name ShipBroker.
     * @return the SHIP_BROKER
     */
    public String getShipBroker() {
        return (String) getAttributeInternal(SHIPBROKER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_BROKER using the alias name ShipBroker.
     * @param value value to set the SHIP_BROKER
     */
    public void setShipBroker(String value) {
        setAttributeInternal(SHIPBROKER, value);
    }

    /**
     * Gets the attribute value for FG_COMPLETION_DATE using the alias name FgCompletionDate.
     * @return the FG_COMPLETION_DATE
     */
    public Date getFgCompletionDate() {
        return (Date) getAttributeInternal(FGCOMPLETIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for FG_COMPLETION_DATE using the alias name FgCompletionDate.
     * @param value value to set the FG_COMPLETION_DATE
     */
    public void setFgCompletionDate(Date value) {
        setAttributeInternal(FGCOMPLETIONDATE, value);
    }

    /**
     * Gets the attribute value for WORK_START_DATE using the alias name WorkStartDate.
     * @return the WORK_START_DATE
     */
    public Date getWorkStartDate() {
        return (Date) getAttributeInternal(WORKSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for WORK_START_DATE using the alias name WorkStartDate.
     * @param value value to set the WORK_START_DATE
     */
    public void setWorkStartDate(Date value) {
        setAttributeInternal(WORKSTARTDATE, value);
    }

    /**
     * Gets the attribute value for SHIP_PRICE using the alias name ShipPrice.
     * @return the SHIP_PRICE
     */
    public Number getShipPrice() {
        return (Number) getAttributeInternal(SHIPPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_PRICE using the alias name ShipPrice.
     * @param value value to set the SHIP_PRICE
     */
    public void setShipPrice(Number value) {
        setAttributeInternal(SHIPPRICE, value);
    }

    /**
     * Gets the attribute value for SHIP_PLANT using the alias name ShipPlant.
     * @return the SHIP_PLANT
     */
    public String getShipPlant() {
        return (String) getAttributeInternal(SHIPPLANT);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_PLANT using the alias name ShipPlant.
     * @param value value to set the SHIP_PLANT
     */
    public void setShipPlant(String value) {
        setAttributeInternal(SHIPPLANT, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_DATE using the alias name EffectiveDate.
     * @return the EFFECTIVE_DATE
     */
    public Date getEffectiveDate() {
        return (Date) getAttributeInternal(EFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_DATE using the alias name EffectiveDate.
     * @param value value to set the EFFECTIVE_DATE
     */
    public void setEffectiveDate(Date value) {
        setAttributeInternal(EFFECTIVEDATE, value);
    }

    /**
     * Gets the attribute value for SHIP_CLSFCT_SOCIETY using the alias name ShipClsfctSociety.
     * @return the SHIP_CLSFCT_SOCIETY
     */
    public String getShipClsfctSociety() {
        return (String) getAttributeInternal(SHIPCLSFCTSOCIETY);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_CLSFCT_SOCIETY using the alias name ShipClsfctSociety.
     * @param value value to set the SHIP_CLSFCT_SOCIETY
     */
    public void setShipClsfctSociety(String value) {
        setAttributeInternal(SHIPCLSFCTSOCIETY, value);
    }

    /**
     * Gets the attribute value for IMO_NO using the alias name ImoNo.
     * @return the IMO_NO
     */
    public String getImoNo() {
        return (String) getAttributeInternal(IMONO);
    }

    /**
     * Sets <code>value</code> as attribute value for IMO_NO using the alias name ImoNo.
     * @param value value to set the IMO_NO
     */
    public void setImoNo(String value) {
        setAttributeInternal(IMONO, value);
    }

    /**
     * Gets the attribute value for PRICE using the alias name Price.
     * @return the PRICE
     */
    public Number getPrice() {
        return (Number) getAttributeInternal(PRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICE using the alias name Price.
     * @param value value to set the PRICE
     */
    public void setPrice(Number value) {
        setAttributeInternal(PRICE, value);
    }

    /**
     * Gets the attribute value for CONTRACT_TYPE using the alias name ContractType1.
     * @return the CONTRACT_TYPE
     */
    public String getContractType1() {
        return (String) getAttributeInternal(CONTRACTTYPE1);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_TYPE using the alias name ContractType1.
     * @param value value to set the CONTRACT_TYPE
     */
    public void setContractType1(String value) {
        setAttributeInternal(CONTRACTTYPE1, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status1.
     * @return the STATUS
     */
    public String getStatus1() {
        return (String) getAttributeInternal(STATUS1);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status1.
     * @param value value to set the STATUS
     */
    public void setStatus1(String value) {
        setAttributeInternal(STATUS1, value);
    }

    /**
     * Gets the attribute value for SHIP_NO_INTERNAL using the alias name ShipNoInternal1.
     * @return the SHIP_NO_INTERNAL
     */
    public String getShipNoInternal1() {
        return (String) getAttributeInternal(SHIPNOINTERNAL1);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_NO_INTERNAL using the alias name ShipNoInternal1.
     * @param value value to set the SHIP_NO_INTERNAL
     */
    public void setShipNoInternal1(String value) {
        setAttributeInternal(SHIPNOINTERNAL1, value);
    }

    /**
     * Gets the attribute value for LINE_NO using the alias name LineNo.
     * @return the LINE_NO
     */
    public Number getLineNo() {
        return (Number) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NO using the alias name LineNo.
     * @param value value to set the LINE_NO
     */
    public void setLineNo(Number value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for SHIP_NAME using the alias name ShipName.
     * @return the SHIP_NAME
     */
    public String getShipName() {
        return (String) getAttributeInternal(SHIPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_NAME using the alias name ShipName.
     * @param value value to set the SHIP_NAME
     */
    public void setShipName(String value) {
        setAttributeInternal(SHIPNAME, value);
    }

    /**
     * Gets the attribute value for SIGN_OFF_DATE using the alias name SignOffDate.
     * @return the SIGN_OFF_DATE
     */
    public Date getSignOffDate() {
        return (Date) getAttributeInternal(SIGNOFFDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SIGN_OFF_DATE using the alias name SignOffDate.
     * @param value value to set the SIGN_OFF_DATE
     */
    public void setSignOffDate(Date value) {
        setAttributeInternal(SIGNOFFDATE, value);
    }

    /**
     * Gets the attribute value for MEMO using the alias name Memo1.
     * @return the MEMO
     */
    public String getMemo1() {
        return (String) getAttributeInternal(MEMO1);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMO using the alias name Memo1.
     * @param value value to set the MEMO
     */
    public void setMemo1(String value) {
        setAttributeInternal(MEMO1, value);
    }

    /**
     * Gets the attribute value for OWNER_TYPE using the alias name OwnerType.
     * @return the OWNER_TYPE
     */
    public String getOwnerType() {
        return (String) getAttributeInternal(OWNERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for OWNER_TYPE using the alias name OwnerType.
     * @param value value to set the OWNER_TYPE
     */
    public void setOwnerType(String value) {
        setAttributeInternal(OWNERTYPE, value);
    }

    /**
     * Gets the attribute value for BROKER_TYPE using the alias name BrokerType.
     * @return the BROKER_TYPE
     */
    public String getBrokerType() {
        return (String) getAttributeInternal(BROKERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BROKER_TYPE using the alias name BrokerType.
     * @param value value to set the BROKER_TYPE
     */
    public void setBrokerType(String value) {
        setAttributeInternal(BROKERTYPE, value);
    }

    /**
     * Gets the attribute value for PLANT_TYPE using the alias name PlantType.
     * @return the PLANT_TYPE
     */
    public String getPlantType() {
        return (String) getAttributeInternal(PLANTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PLANT_TYPE using the alias name PlantType.
     * @param value value to set the PLANT_TYPE
     */
    public void setPlantType(String value) {
        setAttributeInternal(PLANTTYPE, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for SHIP_MNFT_NO using the alias name ShipMnftNo.
     * @return the SHIP_MNFT_NO
     */
    public String getShipMnftNo() {
        return (String) getAttributeInternal(SHIPMNFTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_MNFT_NO using the alias name ShipMnftNo.
     * @param value value to set the SHIP_MNFT_NO
     */
    public void setShipMnftNo(String value) {
        setAttributeInternal(SHIPMNFTNO, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public Number getExchangeRate() {
        return (Number) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(Number value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for SHIP_OWNER using the alias name ShipOwner.
     * @return the SHIP_OWNER
     */
    public String getShipOwner() {
        return (String) getAttributeInternal(SHIPOWNER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_OWNER using the alias name ShipOwner.
     * @param value value to set the SHIP_OWNER
     */
    public void setShipOwner(String value) {
        setAttributeInternal(SHIPOWNER, value);
    }

    /**
     * Gets the attribute value for ID using the alias name IdofLine.
     * @return the ID
     */
    public Number getIdofLine() {
        return (Number) getAttributeInternal(IDOFLINE);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name IdofLine.
     * @param value value to set the ID
     */
    public void setIdofLine(Number value) {
        setAttributeInternal(IDOFLINE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_NAME using the alias name PaymentName.
     * @return the PAYMENT_NAME
     */
    public String getPaymentName() {
        return (String) getAttributeInternal(PAYMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_NAME using the alias name PaymentName.
     * @param value value to set the PAYMENT_NAME
     */
    public void setPaymentName(String value) {
        setAttributeInternal(PAYMENTNAME, value);
    }

    /**
     * Gets the attribute value for PAYMENT_PLAN_DATE using the alias name PaymentPlanDate.
     * @return the PAYMENT_PLAN_DATE
     */
    public Date getPaymentPlanDate() {
        return (Date) getAttributeInternal(PAYMENTPLANDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_PLAN_DATE using the alias name PaymentPlanDate.
     * @param value value to set the PAYMENT_PLAN_DATE
     */
    public void setPaymentPlanDate(Date value) {
        setAttributeInternal(PAYMENTPLANDATE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_PLAN_AMOUNT using the alias name PaymentPlanAmount.
     * @return the PAYMENT_PLAN_AMOUNT
     */
    public Number getPaymentPlanAmount() {
        return (Number) getAttributeInternal(PAYMENTPLANAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_PLAN_AMOUNT using the alias name PaymentPlanAmount.
     * @param value value to set the PAYMENT_PLAN_AMOUNT
     */
    public void setPaymentPlanAmount(Number value) {
        setAttributeInternal(PAYMENTPLANAMOUNT, value);
    }

    /**
     * Gets the attribute value for PAYMENT_PLAN_INVOICE_DATE using the alias name PaymentPlanInvoiceDate.
     * @return the PAYMENT_PLAN_INVOICE_DATE
     */
    public Date getPaymentPlanInvoiceDate() {
        return (Date) getAttributeInternal(PAYMENTPLANINVOICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_PLAN_INVOICE_DATE using the alias name PaymentPlanInvoiceDate.
     * @param value value to set the PAYMENT_PLAN_INVOICE_DATE
     */
    public void setPaymentPlanInvoiceDate(Date value) {
        setAttributeInternal(PAYMENTPLANINVOICEDATE, value);
    }

    /**
     * Gets the attribute value for MEMO using the alias name Memo2.
     * @return the MEMO
     */
    public String getMemo2() {
        return (String) getAttributeInternal(MEMO2);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMO using the alias name Memo2.
     * @param value value to set the MEMO
     */
    public void setMemo2(String value) {
        setAttributeInternal(MEMO2, value);
    }

    /**
     * Gets the attribute value for ID using the alias name Id1.
     * @return the ID
     */
    public Number getId1() {
        return (Number) getAttributeInternal(ID1);
    }

    /**
     * Sets <code>value</code> as attribute value for ID using the alias name Id1.
     * @param value value to set the ID
     */
    public void setId1(Number value) {
        setAttributeInternal(ID1, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @return the CUSTOMER_ID
     */
    public String getCustomerId() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_ID using the alias name CustomerId.
     * @param value value to set the CUSTOMER_ID
     */
    public void setCustomerId(String value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for CUSTOMER_CONTACTOR using the alias name CustomerContactor.
     * @return the CUSTOMER_CONTACTOR
     */
    public String getCustomerContactor() {
        return (String) getAttributeInternal(CUSTOMERCONTACTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for CUSTOMER_CONTACTOR using the alias name CustomerContactor.
     * @param value value to set the CUSTOMER_CONTACTOR
     */
    public void setCustomerContactor(String value) {
        setAttributeInternal(CUSTOMERCONTACTOR, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ContractLinePaymentsView.
     */
    public Row getContractLinePaymentsView() {
        return (Row)getAttributeInternal(CONTRACTLINEPAYMENTSVIEW);
    }

    /**
     * Sets the master-detail link ContractLinePaymentsView between this object and <code>value</code>.
     */
    public void setContractLinePaymentsView(Row value) {
        setAttributeInternal(CONTRACTLINEPAYMENTSVIEW, value);
    }


    /**
     * Gets the associated <code>Row</code> using master-detail link LinePaymentDetailView.
     */
    public Row getLinePaymentDetailView() {
        return (Row)getAttributeInternal(LINEPAYMENTDETAILVIEW);
    }

    /**
     * Sets the master-detail link LinePaymentDetailView between this object and <code>value</code>.
     */
    public void setLinePaymentDetailView(Row value) {
        setAttributeInternal(LINEPAYMENTDETAILVIEW, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
