package edu.hp.model.vo.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 27 19:08:18 CST 2013
// ---------------------------------------------------------------------
public interface ConfRoomCalendarView extends ViewObject {
    void deleteByPK(String clsRmCalId);

    void queryByPK(String confRmCalId);

    void updateActivityTime(String confRmCalId, Timestamp startTime, Timestamp endTime);

    void updateEndTime(String clsRmCalId, Timestamp endTime);

    void newRow(String userDisplayName, String userId);

    void findByUserid(String userId);

    void findByState(String state);
}
