package edu.hp.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 15 15:12:37 CST 2013
// ---------------------------------------------------------------------
public interface GroupsView extends ViewObject {
    void findByName(String grpName);
}
