package edu.hp.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 08 21:08:30 CST 2013
// ---------------------------------------------------------------------
public interface PurchaseOrderLinesView extends ViewObject {
    void newRow();
}
