package edu.hp.model.vo.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 16 20:19:51 CST 2013
// ---------------------------------------------------------------------
public interface VehicleSubTaskView extends ViewObject {
    void deleteTargetRow(String masterId);

    void updateTargetRow(String masterId, Timestamp start, Timestamp end);
}
