package edu.hp.model.eo;

import edu.hp.model.common.Constants;

import java.math.BigDecimal;

import java.text.DecimalFormat;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 26 18:53:14 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClassroomBatchReservationImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Id {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getId();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setId((DBSequence)value);
            }
        }
        ,
        BatchNo {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getBatchNo();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setBatchNo((String)value);
            }
        }
        ,
        ActTitle {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getActTitle();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setActTitle((String)value);
            }
        }
        ,
        ActStartTime {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getActStartTime();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setActStartTime((Timestamp)value);
            }
        }
        ,
        ActEndTime {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getActEndTime();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setActEndTime((Timestamp)value);
            }
        }
        ,
        UserId {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getUserId();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setUserId((String)value);
            }
        }
        ,
        UserDisplayName {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getUserDisplayName();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setUserDisplayName((String)value);
            }
        }
        ,
        NumOfPeople {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getNumOfPeople();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setNumOfPeople((BigDecimal)value);
            }
        }
        ,
        Classroom {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getClassroom();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setClassroom((String)value);
            }
        }
        ,
        Comments {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getComments();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setComments((String)value);
            }
        }
        ,
        BatchEffectiveDate {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getBatchEffectiveDate();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setBatchEffectiveDate((Timestamp)value);
            }
        }
        ,
        BatchExpireDate {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getBatchExpireDate();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setBatchExpireDate((Timestamp)value);
            }
        }
        ,
        RecurrenceType {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getRecurrenceType();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setRecurrenceType((String)value);
            }
        }
        ,
        FstWkMon {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getFstWkMon();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setFstWkMon((String)value);
            }
        }
        ,
        FstWkTue {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getFstWkTue();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setFstWkTue((String)value);
            }
        }
        ,
        FstWkWed {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getFstWkWed();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setFstWkWed((String)value);
            }
        }
        ,
        FstWkThu {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getFstWkThu();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setFstWkThu((String)value);
            }
        }
        ,
        FstWkFri {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getFstWkFri();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setFstWkFri((String)value);
            }
        }
        ,
        FstWkSat {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getFstWkSat();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setFstWkSat((String)value);
            }
        }
        ,
        FstWkSun {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getFstWkSun();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setFstWkSun((String)value);
            }
        }
        ,
        SndWkMon {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getSndWkMon();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setSndWkMon((String)value);
            }
        }
        ,
        SndWkTue {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getSndWkTue();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setSndWkTue((String)value);
            }
        }
        ,
        SndWkWed {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getSndWkWed();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setSndWkWed((String)value);
            }
        }
        ,
        SndWkThu {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getSndWkThu();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setSndWkThu((String)value);
            }
        }
        ,
        SndWkFri {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getSndWkFri();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setSndWkFri((String)value);
            }
        }
        ,
        SndWkSat {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getSndWkSat();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setSndWkSat((String)value);
            }
        }
        ,
        SndWkSun {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getSndWkSun();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setSndWkSun((String)value);
            }
        }
        ,
        LocationId {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getLocationId();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setLocationId((String)value);
            }
        }
        ,
        LocationName {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getLocationName();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setLocationName((String)value);
            }
        }
        ,
        ClassroomId {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getClassroomId();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setClassroomId((String)value);
            }
        }
        ,
        AllDay {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getAllDay();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setAllDay((String)value);
            }
        }
        ,
        BatchInstances {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getBatchInstances();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BatchNoSeq {
            public Object get(ClassroomBatchReservationImpl obj) {
                return obj.getBatchNoSeq();
            }

            public void put(ClassroomBatchReservationImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ClassroomBatchReservationImpl object);

        public abstract void put(ClassroomBatchReservationImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int BATCHNO = AttributesEnum.BatchNo.index();
    public static final int ACTTITLE = AttributesEnum.ActTitle.index();
    public static final int ACTSTARTTIME = AttributesEnum.ActStartTime.index();
    public static final int ACTENDTIME = AttributesEnum.ActEndTime.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERDISPLAYNAME = AttributesEnum.UserDisplayName.index();
    public static final int NUMOFPEOPLE = AttributesEnum.NumOfPeople.index();
    public static final int CLASSROOM = AttributesEnum.Classroom.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int BATCHEFFECTIVEDATE = AttributesEnum.BatchEffectiveDate.index();
    public static final int BATCHEXPIREDATE = AttributesEnum.BatchExpireDate.index();
    public static final int RECURRENCETYPE = AttributesEnum.RecurrenceType.index();
    public static final int FSTWKMON = AttributesEnum.FstWkMon.index();
    public static final int FSTWKTUE = AttributesEnum.FstWkTue.index();
    public static final int FSTWKWED = AttributesEnum.FstWkWed.index();
    public static final int FSTWKTHU = AttributesEnum.FstWkThu.index();
    public static final int FSTWKFRI = AttributesEnum.FstWkFri.index();
    public static final int FSTWKSAT = AttributesEnum.FstWkSat.index();
    public static final int FSTWKSUN = AttributesEnum.FstWkSun.index();
    public static final int SNDWKMON = AttributesEnum.SndWkMon.index();
    public static final int SNDWKTUE = AttributesEnum.SndWkTue.index();
    public static final int SNDWKWED = AttributesEnum.SndWkWed.index();
    public static final int SNDWKTHU = AttributesEnum.SndWkThu.index();
    public static final int SNDWKFRI = AttributesEnum.SndWkFri.index();
    public static final int SNDWKSAT = AttributesEnum.SndWkSat.index();
    public static final int SNDWKSUN = AttributesEnum.SndWkSun.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int LOCATIONNAME = AttributesEnum.LocationName.index();
    public static final int CLASSROOMID = AttributesEnum.ClassroomId.index();
    public static final int ALLDAY = AttributesEnum.AllDay.index();
    public static final int BATCHINSTANCES = AttributesEnum.BatchInstances.index();
    public static final int BATCHNOSEQ = AttributesEnum.BatchNoSeq.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ClassroomBatchReservationImpl() {
    }


    //    protected void doDML(int operation, TransactionEvent e) {
//        if (operation == DML_INSERT || operation == DML_UPDATE) {
//            if (this.getAllDay().equals("ALLDAY")) {
//                Timestamp actEndTime = this.getActEndTime();
//                if (actEndTime != null) {
//                    Calendar calendar = Calendar.getInstance();
//                    calendar.setTimeInMillis(actEndTime.getTime());
//                    calendar.set(Calendar.HOUR_OF_DAY, 23);
//                    calendar.set(Calendar.MINUTE, 59);
//                    calendar.set(Calendar.SECOND, 59);
//                    this.setActEndTime(new Timestamp(calendar.getTimeInMillis()));
//                }
//                Timestamp actStartTime = this.getActStartTime();
//                if (actStartTime != null) {
//                    Calendar calendar = Calendar.getInstance();
//                    calendar.setTimeInMillis(actStartTime.getTime());
//                    calendar.set(Calendar.HOUR_OF_DAY, 0);
//                    calendar.set(Calendar.MINUTE, 0);
//                    calendar.set(Calendar.SECOND, 0);
//                    this.setActEndTime(new Timestamp(calendar.getTimeInMillis()));
//                }
//            }
//        }
//
//        super.doDML(operation, e);
//    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("edu.hp.model.eo.ClassroomBatchReservation");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        
        super.create(attributeList);
        RowSet batchNoSeq = this.getBatchNoSeq();
        batchNoSeq.setRangeSize(-1);
        batchNoSeq.executeQuery();
        Row[] allRowsInRange = batchNoSeq.getAllRowsInRange();
        if (allRowsInRange != null && allRowsInRange.length > 0) {
            String currentValue = (String)(allRowsInRange[0].getAttribute("SEQ"));
            DecimalFormat format = new DecimalFormat("00000");
            String batchNo = format.format(new Integer(currentValue).intValue() + 1);
            String finalBatchNO = Constants.CLSRM_BATCH_PREFIX + batchNo;
        
            this.setBatchNo(finalBatchNO);
        }
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the value of Id
     */
    public DBSequence getId() {
        return (DBSequence)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(DBSequence value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for BatchNo, using the alias name BatchNo.
     * @return the value of BatchNo
     */
    public String getBatchNo() {
        return (String)getAttributeInternal(BATCHNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchNo.
     * @param value value to set the BatchNo
     */
    public void setBatchNo(String value) {
        setAttributeInternal(BATCHNO, value);
    }

    /**
     * Gets the attribute value for ActTitle, using the alias name ActTitle.
     * @return the value of ActTitle
     */
    public String getActTitle() {
        return (String)getAttributeInternal(ACTTITLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActTitle.
     * @param value value to set the ActTitle
     */
    public void setActTitle(String value) {
        setAttributeInternal(ACTTITLE, value);
    }

    /**
     * Gets the attribute value for ActStartTime, using the alias name ActStartTime.
     * @return the value of ActStartTime
     */
    public Timestamp getActStartTime() {
        return (Timestamp)getAttributeInternal(ACTSTARTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActStartTime.
     * @param value value to set the ActStartTime
     */
    public void setActStartTime(Timestamp value) {
        setAttributeInternal(ACTSTARTTIME, value);
    }

    /**
     * Gets the attribute value for ActEndTime, using the alias name ActEndTime.
     * @return the value of ActEndTime
     */
    public Timestamp getActEndTime() {
        return (Timestamp)getAttributeInternal(ACTENDTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActEndTime.
     * @param value value to set the ActEndTime
     */
    public void setActEndTime(Timestamp value) {
        setAttributeInternal(ACTENDTIME, value);
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public String getUserId() {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for UserDisplayName, using the alias name UserDisplayName.
     * @return the value of UserDisplayName
     */
    public String getUserDisplayName() {
        return (String)getAttributeInternal(USERDISPLAYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserDisplayName.
     * @param value value to set the UserDisplayName
     */
    public void setUserDisplayName(String value) {
        setAttributeInternal(USERDISPLAYNAME, value);
    }

    /**
     * Gets the attribute value for NumOfPeople, using the alias name NumOfPeople.
     * @return the value of NumOfPeople
     */
    public BigDecimal getNumOfPeople() {
        return (BigDecimal)getAttributeInternal(NUMOFPEOPLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NumOfPeople.
     * @param value value to set the NumOfPeople
     */
    public void setNumOfPeople(BigDecimal value) {
        setAttributeInternal(NUMOFPEOPLE, value);
    }

    /**
     * Gets the attribute value for Classroom, using the alias name Classroom.
     * @return the value of Classroom
     */
    public String getClassroom() {
        return (String)getAttributeInternal(CLASSROOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Classroom.
     * @param value value to set the Classroom
     */
    public void setClassroom(String value) {
        setAttributeInternal(CLASSROOM, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the value of Comments
     */
    public String getComments() {
        return (String)getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for BatchEffectiveDate, using the alias name BatchEffectiveDate.
     * @return the value of BatchEffectiveDate
     */
    public Timestamp getBatchEffectiveDate() {
        return (Timestamp)getAttributeInternal(BATCHEFFECTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchEffectiveDate.
     * @param value value to set the BatchEffectiveDate
     */
    public void setBatchEffectiveDate(Timestamp value) {
        setAttributeInternal(BATCHEFFECTIVEDATE, value);
    }

    /**
     * Gets the attribute value for BatchExpireDate, using the alias name BatchExpireDate.
     * @return the value of BatchExpireDate
     */
    public Timestamp getBatchExpireDate() {
        return (Timestamp)getAttributeInternal(BATCHEXPIREDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchExpireDate.
     * @param value value to set the BatchExpireDate
     */
    public void setBatchExpireDate(Timestamp value) {
        setAttributeInternal(BATCHEXPIREDATE, value);
    }

    /**
     * Gets the attribute value for RecurrenceType, using the alias name RecurrenceType.
     * @return the value of RecurrenceType
     */
    public String getRecurrenceType() {
        return (String)getAttributeInternal(RECURRENCETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecurrenceType.
     * @param value value to set the RecurrenceType
     */
    public void setRecurrenceType(String value) {
        setAttributeInternal(RECURRENCETYPE, value);
    }

    /**
     * Gets the attribute value for FstWkMon, using the alias name FstWkMon.
     * @return the value of FstWkMon
     */
    public String getFstWkMon() {
        return (String)getAttributeInternal(FSTWKMON);
    }

    /**
     * Sets <code>value</code> as the attribute value for FstWkMon.
     * @param value value to set the FstWkMon
     */
    public void setFstWkMon(String value) {
        setAttributeInternal(FSTWKMON, value);
    }

    /**
     * Gets the attribute value for FstWkTue, using the alias name FstWkTue.
     * @return the value of FstWkTue
     */
    public String getFstWkTue() {
        return (String)getAttributeInternal(FSTWKTUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FstWkTue.
     * @param value value to set the FstWkTue
     */
    public void setFstWkTue(String value) {
        setAttributeInternal(FSTWKTUE, value);
    }

    /**
     * Gets the attribute value for FstWkWed, using the alias name FstWkWed.
     * @return the value of FstWkWed
     */
    public String getFstWkWed() {
        return (String)getAttributeInternal(FSTWKWED);
    }

    /**
     * Sets <code>value</code> as the attribute value for FstWkWed.
     * @param value value to set the FstWkWed
     */
    public void setFstWkWed(String value) {
        setAttributeInternal(FSTWKWED, value);
    }

    /**
     * Gets the attribute value for FstWkThu, using the alias name FstWkThu.
     * @return the value of FstWkThu
     */
    public String getFstWkThu() {
        return (String)getAttributeInternal(FSTWKTHU);
    }

    /**
     * Sets <code>value</code> as the attribute value for FstWkThu.
     * @param value value to set the FstWkThu
     */
    public void setFstWkThu(String value) {
        setAttributeInternal(FSTWKTHU, value);
    }

    /**
     * Gets the attribute value for FstWkFri, using the alias name FstWkFri.
     * @return the value of FstWkFri
     */
    public String getFstWkFri() {
        return (String)getAttributeInternal(FSTWKFRI);
    }

    /**
     * Sets <code>value</code> as the attribute value for FstWkFri.
     * @param value value to set the FstWkFri
     */
    public void setFstWkFri(String value) {
        setAttributeInternal(FSTWKFRI, value);
    }

    /**
     * Gets the attribute value for FstWkSat, using the alias name FstWkSat.
     * @return the value of FstWkSat
     */
    public String getFstWkSat() {
        return (String)getAttributeInternal(FSTWKSAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FstWkSat.
     * @param value value to set the FstWkSat
     */
    public void setFstWkSat(String value) {
        setAttributeInternal(FSTWKSAT, value);
    }

    /**
     * Gets the attribute value for FstWkSun, using the alias name FstWkSun.
     * @return the value of FstWkSun
     */
    public String getFstWkSun() {
        return (String)getAttributeInternal(FSTWKSUN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FstWkSun.
     * @param value value to set the FstWkSun
     */
    public void setFstWkSun(String value) {
        setAttributeInternal(FSTWKSUN, value);
    }

    /**
     * Gets the attribute value for SndWkMon, using the alias name SndWkMon.
     * @return the value of SndWkMon
     */
    public String getSndWkMon() {
        return (String)getAttributeInternal(SNDWKMON);
    }

    /**
     * Sets <code>value</code> as the attribute value for SndWkMon.
     * @param value value to set the SndWkMon
     */
    public void setSndWkMon(String value) {
        setAttributeInternal(SNDWKMON, value);
    }

    /**
     * Gets the attribute value for SndWkTue, using the alias name SndWkTue.
     * @return the value of SndWkTue
     */
    public String getSndWkTue() {
        return (String)getAttributeInternal(SNDWKTUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SndWkTue.
     * @param value value to set the SndWkTue
     */
    public void setSndWkTue(String value) {
        setAttributeInternal(SNDWKTUE, value);
    }

    /**
     * Gets the attribute value for SndWkWed, using the alias name SndWkWed.
     * @return the value of SndWkWed
     */
    public String getSndWkWed() {
        return (String)getAttributeInternal(SNDWKWED);
    }

    /**
     * Sets <code>value</code> as the attribute value for SndWkWed.
     * @param value value to set the SndWkWed
     */
    public void setSndWkWed(String value) {
        setAttributeInternal(SNDWKWED, value);
    }

    /**
     * Gets the attribute value for SndWkThu, using the alias name SndWkThu.
     * @return the value of SndWkThu
     */
    public String getSndWkThu() {
        return (String)getAttributeInternal(SNDWKTHU);
    }

    /**
     * Sets <code>value</code> as the attribute value for SndWkThu.
     * @param value value to set the SndWkThu
     */
    public void setSndWkThu(String value) {
        setAttributeInternal(SNDWKTHU, value);
    }

    /**
     * Gets the attribute value for SndWkFri, using the alias name SndWkFri.
     * @return the value of SndWkFri
     */
    public String getSndWkFri() {
        return (String)getAttributeInternal(SNDWKFRI);
    }

    /**
     * Sets <code>value</code> as the attribute value for SndWkFri.
     * @param value value to set the SndWkFri
     */
    public void setSndWkFri(String value) {
        setAttributeInternal(SNDWKFRI, value);
    }

    /**
     * Gets the attribute value for SndWkSat, using the alias name SndWkSat.
     * @return the value of SndWkSat
     */
    public String getSndWkSat() {
        return (String)getAttributeInternal(SNDWKSAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SndWkSat.
     * @param value value to set the SndWkSat
     */
    public void setSndWkSat(String value) {
        setAttributeInternal(SNDWKSAT, value);
    }

    /**
     * Gets the attribute value for SndWkSun, using the alias name SndWkSun.
     * @return the value of SndWkSun
     */
    public String getSndWkSun() {
        return (String)getAttributeInternal(SNDWKSUN);
    }

    /**
     * Sets <code>value</code> as the attribute value for SndWkSun.
     * @param value value to set the SndWkSun
     */
    public void setSndWkSun(String value) {
        setAttributeInternal(SNDWKSUN, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the value of LocationId
     */
    public String getLocationId() {
        return (String)getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for LocationName, using the alias name LocationName.
     * @return the value of LocationName
     */
    public String getLocationName() {
        return (String)getAttributeInternal(LOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationName.
     * @param value value to set the LocationName
     */
    public void setLocationName(String value) {
        setAttributeInternal(LOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for ClassroomId, using the alias name ClassroomId.
     * @return the value of ClassroomId
     */
    public String getClassroomId() {
        return (String)getAttributeInternal(CLASSROOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClassroomId.
     * @param value value to set the ClassroomId
     */
    public void setClassroomId(String value) {
        setAttributeInternal(CLASSROOMID, value);
    }

    /**
     * Gets the attribute value for AllDay, using the alias name AllDay.
     * @return the value of AllDay
     */
    public String getAllDay() {
        return (String)getAttributeInternal(ALLDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllDay.
     * @param value value to set the AllDay
     */
    public void setAllDay(String value) {
        setAttributeInternal(ALLDAY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBatchInstances() {
        return (RowIterator)getAttributeInternal(BATCHINSTANCES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BatchNoSeq.
     */
    public RowSet getBatchNoSeq() {
        return (RowSet)getAttributeInternal(BATCHNOSEQ);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }


}
