package edu.hp.model.eo;

import edu.hp.model.common.Constants;

import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 31 18:01:10 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VehicleCalendarImpl extends EntityImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VehicleCalendarImpl() {
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence id) {
        return new Key(new Object[]{id});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("edu.hp.model.eo.VehicleCalendar");
    }


    /**
     * Validation method for VehicleCalendar.
     */
    public boolean validateVehicle() {
        String state = (String)getAttribute("State");
        String vehicleId = (String)getAttribute("VehicleId");
        if(state!=null&&state.equals(Constants.STATE_TRIP_PLANNED)&&vehicleId==null)
            return false;                
        return true;
    }


}
