package edu.hp.model.biz.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 15 15:14:21 CST 2013
// ---------------------------------------------------------------------
public interface HelpdeskCallsAppModule extends ApplicationModule {
    void findByCallerId(String callerId);

    void findByState(String state);

    void findByCallId(String id);
}
