package edu.hp.model.biz.common;

import edu.hp.model.pojo.Notification;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 12 16:04:15 CST 2013
// ---------------------------------------------------------------------
public interface RootAppModule extends ApplicationModule {

    void enableSMS(Boolean enalbed);

    void sendNotification(Notification notification);


    void completeTask(String contextObjectType, String contextObjectId, String roleName);

    void completeTaskForUserId(String contextObjectType, String contextObjectId, String userId);


    void cancelTask(String contextObjectType, String contextObjectId);

    void createTask(String title, String contextObjectType, String contextObjectId, String roleName,
                    String contextTitle);

    void createTaskForUserId(String title, String contextObjectType, String contextObjectId, String userId,
                             String contextTitle);
}
