package com.xy.scpms.model.vo.client;

import com.xy.scpms.model.vo.common.ContractLinePaymentsView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 27 09:44:24 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ContractLinePaymentsViewClient extends ViewUsageImpl implements ContractLinePaymentsView {
    /**
     * This is the default constructor (do not remove).
     */
    public ContractLinePaymentsViewClient() {
    }

    public void setCurrentRowById(oracle.jbo.domain.Number id) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setCurrentRowById",new String [] {"oracle.jbo.domain.Number"},new Object[] {id});
        return;
    }
}
