package edu.hp.model.vo.query.conf.client;

import edu.hp.model.vo.query.conf.common.ConfRmConflictView;

import java.sql.Timestamp;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 27 19:11:53 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConfRmConflictViewClient extends ViewUsageImpl implements ConfRmConflictView {
    /**
     * This is the default constructor (do not remove).
     */
    public ConfRmConflictViewClient() {
    }

    public Boolean ifConflict(Timestamp actStartTime, Timestamp actEndTime, String clsRmId, String actId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"ifConflict",new String [] {"java.sql.Timestamp","java.sql.Timestamp","java.lang.String","java.lang.String"},new Object[] {actStartTime, actEndTime, clsRmId, actId});
        return (Boolean)_ret;
    }
}
