package com.xy.scpms.model.query;


import com.xy.scpms.model.query.common.CustomerView;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 18 19:51:55 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerViewImpl extends ViewObjectImpl implements CustomerView {
    /**
     * This is the default constructor (do not remove).
     */
    public CustomerViewImpl() {
    }
    
    public void setQueryTypeById(String id){
        System.out.println("customer id: " + id);
        this.setApplyViewCriteriaNames(null);
        ViewCriteria criteria = this.getViewCriteria("findById");
        this.applyViewCriteria(criteria);
        this.setcustomerId(id);
        this.executeQuery();
    }
    
    public void setQueryType(String type){
        
        this.setApplyViewCriteriaNames(null);
        ViewCriteria criteria = this.getViewCriteria("filterByType");
//        System.err.println("customer query type is: "+type);
        this.applyViewCriteria(criteria);
        this.setcustType(type);
        this.executeQuery();
    }

    /**
     * Returns the variable value for custNameBind.
     * @return variable value for custNameBind
     */
    public String getcustNameBind() {
        return (String)ensureVariableManager().getVariableValue("custNameBind");
    }

    /**
     * Sets <code>value</code> for variable custNameBind.
     * @param value value to bind as custNameBind
     */
    public void setcustNameBind(String value) {
        ensureVariableManager().setVariableValue("custNameBind", value);
    }

    /**
     * Returns the variable value for custType.
     * @return variable value for custType
     */
    public String getcustType() {
        return (String)ensureVariableManager().getVariableValue("custType");
    }

    /**
     * Sets <code>value</code> for variable custType.
     * @param value value to bind as custType
     */
    public void setcustType(String value) {
        ensureVariableManager().setVariableValue("custType", value);
    }

    /**
     * Returns the variable value for customerId.
     * @return variable value for customerId
     */
    public String getcustomerId() {
        return (String)ensureVariableManager().getVariableValue("customerId");
    }

    /**
     * Sets <code>value</code> for variable customerId.
     * @param value value to bind as customerId
     */
    public void setcustomerId(String value) {
        ensureVariableManager().setVariableValue("customerId", value);
    }
}
