package edu.hp.model.vo.query.note;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 12 15:34:58 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReceiverMobileListViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ReceiverMobileListViewImpl() {
    }

    /**
     * Returns the bind variable value for roleId.
     * @return bind variable value for roleId
     */
    public String getroleId() {
        return (String)getNamedWhereClauseParam("roleId");
    }

    /**
     * Sets <code>value</code> for bind variable roleId.
     * @param value value to bind as roleId
     */
    public void setroleId(String value) {
        setNamedWhereClauseParam("roleId", value);
    }
}
