package com.xy.scpms.model.query.search.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 17:09:20 CST 2011
// ---------------------------------------------------------------------
public interface SearchContractByMgrIdView extends ViewObject {
    void setMgrIdBind(String value);
}
