SPOOL script1.log

SET SQLBLANKLINES ON
PROMPT create tablespace 'SYSAUX'
CREATE TABLESPACE SYSAUX 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

PROMPT create tablespace 'SYSTEM'
CREATE TABLESPACE SYSTEM 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT MANUAL 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

PROMPT create tablespace 'TEMP'
CREATE TEMPORARY TABLESPACE TEMP 
    EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1048576;

PROMPT create tablespace 'UNDO'
CREATE UNDO TABLESPACE UNDO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
    RETENTION NOGUARANTEE;

PROMPT create tablespace 'USERS'
CREATE TABLESPACE USERS 
    BLOCKSIZE 8192 
    DEFAULT NOCOMPRESS 
    ONLINE 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

PROMPT create table 'APPROVAL_IN_PROCESS'
CREATE TABLE OM.APPROVAL_IN_PROCESS 
(
  ID NUMBER NOT NULL 
, ROUTING_NO NUMBER 
, SEQ NUMBER 
, APPROVER VARCHAR2(50 BYTE) 
, OUTCOME VARCHAR2(20 BYTE) 
, CONTRACT_ID NUMBER 
, MEMO VARCHAR2(500 BYTE) 
, APPROVAL_DATE DATE 
, APPROVAL_ROLE VARCHAR2(20 BYTE) 
, CONTRACT_NO VARCHAR2(100 BYTE) 
, CREATOR VARCHAR2(20 BYTE) 
, TYPE VARCHAR2(20 BYTE) 
, CONSTRAINT APPROVAL_IN_PROCESS_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.APPROVAL_IN_PROCESS_PK ON OM.APPROVAL_IN_PROCESS (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'APPROVAL_ROUTING'
CREATE TABLE OM.APPROVAL_ROUTING 
(
  ROUTING_NO NUMBER NOT NULL 
, SEQ NUMBER NOT NULL 
, APPROVER VARCHAR2(50 BYTE) NOT NULL 
, ID NUMBER NOT NULL 
, CONSTRAINT APPROVAL_ROUTING_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.APPROVAL_ROUTING_PK ON OM.APPROVAL_ROUTING (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'CHANGE_HISTORY'
CREATE TABLE OM.CHANGE_HISTORY 
(
  ID NUMBER NOT NULL 
, TABLE_NAME VARCHAR2(100 BYTE) 
, COLUMN_NAME VARCHAR2(100 BYTE) 
, OPERATION VARCHAR2(20 BYTE) 
, OLD_VALUE VARCHAR2(1000 BYTE) 
, NEW_VALUE VARCHAR2(1000 BYTE) 
, CHANGE_DATE DATE 
, CHANGE_BY VARCHAR2(50 BYTE) 
, ROW_ID NUMBER 
, CONSTRAINT CHANGE_HISTORY_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.CHANGE_HISTORY_PK ON OM.CHANGE_HISTORY (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'CONTRACT'
CREATE TABLE OM.CONTRACT 
(
  ID NUMBER NOT NULL 
, CONTRACT_NO VARCHAR2(50 BYTE) NOT NULL 
, PROJECT_NAME VARCHAR2(200 BYTE) NOT NULL 
, PROJECT_MANAGER VARCHAR2(20 BYTE) NOT NULL 
, REGION_MANAGER VARCHAR2(20 BYTE) NOT NULL 
, DESIGN_DEPT VARCHAR2(30 BYTE) NOT NULL 
, SHIP_NO_INTERNAL VARCHAR2(200 BYTE) NOT NULL 
, CONTRACT_ENTITY VARCHAR2(300 BYTE) NOT NULL 
, SHIP_MODEL VARCHAR2(100 BYTE) NOT NULL 
, AUTH_TYPE VARCHAR2(20 BYTE) NOT NULL 
, AUTH_NAME VARCHAR2(200 BYTE) 
, AUTHORIZER_TYPE VARCHAR2(20 BYTE) NOT NULL 
, CREATED_BY VARCHAR2(20 BYTE) DEFAULT NULL 
, CREATED_AT DATE DEFAULT NULL 
, DELETED VARCHAR2(1 BYTE) DEFAULT NULL 
, STATUS VARCHAR2(100 BYTE) 
, MEMO VARCHAR2(1000 BYTE) 
, FIRST_DESIGN_FEE NUMBER 
, DESIGN_PHASE VARCHAR2(20 BYTE) 
, CUSTOMER_CONTACTOR NUMBER 
, AGREEMENT_IMG_URL VARCHAR2(100 BYTE) 
, CONTRACT_TYPE VARCHAR2(20 BYTE) 
, PARENT_CONTRACT_ID NUMBER 
, TOTAL_AMOUNT NUMBER 
, REFINED_FLAG VARCHAR2(1 BYTE) 
, CUSTOMER_ID NUMBER 
, CUSTOMER_CONTACT_NAME VARCHAR2(20 BYTE) 
, PARENT_CONTRACT_NO VARCHAR2(50 BYTE) 
, CONSTRAINT CONTRACT_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.CONTRACT_PK ON OM.CONTRACT (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'CONTRACT_ATTACHMENT'
CREATE TABLE OM.CONTRACT_ATTACHMENT 
(
  ID NUMBER NOT NULL 
, CONTRACT_ID NUMBER NOT NULL 
, FILE_NAME VARCHAR2(200 BYTE) 
, FILE_LINK VARCHAR2(500 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, FILE_DESC VARCHAR2(200 BYTE) 
, CREATION_DATE DATE 
, DELETED VARCHAR2(1 BYTE) 
, CONSTRAINT CONTRACT_ATTACHMENT_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.CONTRACT_ATTACHMENT_PK ON OM.CONTRACT_ATTACHMENT (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'CONTRACT_LINE'
CREATE TABLE OM.CONTRACT_LINE 
(
  ID NUMBER NOT NULL 
, HEADER_ID NUMBER 
, LINE_NO NUMBER 
, SHIP_MNFT_NO VARCHAR2(100 BYTE) 
, SHIP_OWNER VARCHAR2(200 BYTE) 
, SHIP_BROKER VARCHAR2(200 BYTE) 
, SHIP_CLSFCT_SOCIETY VARCHAR2(200 BYTE) 
, SHIP_NAME VARCHAR2(200 BYTE) NOT NULL 
, IMO_NO VARCHAR2(200 BYTE) 
, SHIP_NO_INTERNAL VARCHAR2(200 BYTE) 
, CONTRACT_TYPE VARCHAR2(20 BYTE) 
, SIGN_OFF_DATE DATE NOT NULL 
, EFFECTIVE_DATE DATE NOT NULL 
, ABANDON_DATE DATE 
, CREATED_BY VARCHAR2(20 BYTE) DEFAULT NULL 
, CREATED_AT DATE DEFAULT NULL 
, DELETED VARCHAR2(2 BYTE) DEFAULT NULL 
, STATUS VARCHAR2(100 BYTE) 
, MEMO VARCHAR2(1000 BYTE) 
, PRICE NUMBER 
, WORK_START_DATE DATE 
, FG_COMPLETION_DATE DATE 
, SHIP_PLANT VARCHAR2(50 BYTE) 
, CURRENCY VARCHAR2(20 BYTE) 
, EXCHANGE_RATE NUMBER 
, OWNER_TYPE VARCHAR2(50 BYTE) 
, PLANT_TYPE VARCHAR2(50 BYTE) 
, BROKER_TYPE VARCHAR2(50 BYTE) 
, SHIP_PRICE NUMBER 
, ABANDON_FLAG VARCHAR2(1 BYTE) 
, FOUR_CONTRACT_BATCH VARCHAR2(100 BYTE) 
, CONSTRAINT CONTRACT_LINE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.CONTRACT_LINE_PK ON OM.CONTRACT_LINE (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'CONTRACT_LINE_PAYMENTS'
CREATE TABLE OM.CONTRACT_LINE_PAYMENTS 
(
  ID NUMBER NOT NULL 
, LINE_ID NUMBER NOT NULL 
, PAYMENT_NAME VARCHAR2(20 BYTE) NOT NULL 
, PAYMENT_PLAN_DATE DATE NOT NULL 
, PAYMENT_PLAN_AMOUNT NUMBER 
, DELETED VARCHAR2(2 BYTE) DEFAULT NULL 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATED_AT DATE DEFAULT NULL 
, PAYMENT_PLAN_INVOICE_DATE DATE 
, STATUS VARCHAR2(100 BYTE) 
, INVOICE_DATE DATE 
, INVOICE_AMOUNT NUMBER 
, TOTAL_PAYMENT VARCHAR2(20 BYTE) 
, VARIANCE VARCHAR2(20 BYTE) 
, MEMO VARCHAR2(20 BYTE) 
, INVOICE_NUMBER VARCHAR2(100 BYTE) 
, INVOICE_BATCH_ID NUMBER 
, CONSTRAINT CONTRACT_LINE_PAYMENTS_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.CONTRACT_LINE_PAYMENTS_PK ON OM.CONTRACT_LINE_PAYMENTS (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'CUSTOMER'
CREATE TABLE OM.CUSTOMER 
(
  ID NUMBER NOT NULL 
, CUSTOMER_NAME VARCHAR2(200 BYTE) NOT NULL 
, CUSTOMER_BILL_ADDRESS VARCHAR2(2000 BYTE) 
, CUSTOMER_SHIPTO_ADDRESS VARCHAR2(2000 BYTE) 
, CUSTOMER_CONTACT_PERSON VARCHAR2(20 BYTE) 
, CUSTOMER_CODE VARCHAR2(100 BYTE) 
, CUSTOMER_TYPE VARCHAR2(20 BYTE) 
, REGION VARCHAR2(20 BYTE) 
, CUSTOMER_LEVEL VARCHAR2(20 BYTE) 
, PARENT_GROUP VARCHAR2(200 BYTE) 
, PRIMARY_SHIP_TYPE VARCHAR2(50 BYTE) 
, SHIP_GROUP_LEVEL VARCHAR2(20 BYTE) 
, POST_CODE VARCHAR2(20 BYTE) 
, RECENT_ACTION VARCHAR2(200 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATION_DATE DATE 
, OWNER VARCHAR2(20 BYTE) 
, CONSTRAINT CUSTOMER_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.CUSTOMER_PK ON OM.CUSTOMER (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'CUSTOMER_CONTACTS'
CREATE TABLE OM.CUSTOMER_CONTACTS 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(20 BYTE) 
, IMPORTANT_LEVEL VARCHAR2(20 BYTE) 
, DEPARTMENT VARCHAR2(20 BYTE) 
, MOBILE VARCHAR2(40 BYTE) 
, OFFICE_PHONE VARCHAR2(40 BYTE) 
, OFFICE_FAX VARCHAR2(40 BYTE) 
, HOME_PHONE VARCHAR2(40 BYTE) 
, EMAIL VARCHAR2(200 BYTE) 
, IM VARCHAR2(200 BYTE) 
, ADDRESS VARCHAR2(2000 BYTE) 
, MEMO VARCHAR2(20 BYTE) 
, STATUS VARCHAR2(20 BYTE) 
, CUSOMTER_ID NUMBER 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATION_DATE DATE 
, CONSTRAINT CUSTOMER_CONTACTS_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.CUSTOMER_CONTACTS_PK ON OM.CUSTOMER_CONTACTS (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'GROUPMEMBERS'
CREATE TABLE OM.GROUPMEMBERS 
(
  G_NAME VARCHAR2(20 BYTE) NOT NULL 
, G_MEMBER VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT GROUPMEMBERS_PK PRIMARY KEY 
  (
    G_NAME 
  , G_MEMBER 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.GROUPMEMBERS_PK ON OM.GROUPMEMBERS (G_NAME ASC, G_MEMBER ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'GROUPS'
CREATE TABLE OM.GROUPS 
(
  G_NAME VARCHAR2(20 BYTE) NOT NULL 
, G_DESCRIPTION VARCHAR2(200 BYTE) 
, CONSTRAINT GROUPS_PK PRIMARY KEY 
  (
    G_NAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.GROUPS_PK ON OM.GROUPS (G_NAME ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'INVOICE_BATCH'
CREATE TABLE OM.INVOICE_BATCH 
(
  ID NUMBER NOT NULL 
, BATCH_NAME VARCHAR2(100 BYTE) NOT NULL 
, INV_NUM NUMBER 
, STATUS VARCHAR2(20 BYTE) 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATION_DATE DATE 
, MEMO VARCHAR2(200 BYTE) 
, CONSTRAINT INVOICE_BATCH_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.INVOICE_BATCH_PK ON OM.INVOICE_BATCH (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'INVOICE_REQUISITION'
CREATE TABLE OM.INVOICE_REQUISITION 
(
  ID NUMBER NOT NULL 
, REQUESTOR VARCHAR2(20 BYTE) 
, REQUEST_DATE DATE 
, LINE_PAYMENT_ID NUMBER NOT NULL 
, AMOUNT NUMBER 
, STATUS VARCHAR2(20 BYTE) 
, MEMO VARCHAR2(200 BYTE) 
, DEPT_HEAD_APPROVER VARCHAR2(20 BYTE) 
, DEPT_HEAD_OUTCOME VARCHAR2(20 BYTE) 
, DEPT_HEAD_DATE DATE 
, DEPT_HEAD_MEMO VARCHAR2(100 BYTE) 
, MRKT_HEAD_APPROVER VARCHAR2(20 BYTE) 
, MRKT_HEAD_OUTCOME VARCHAR2(20 BYTE) 
, MRKT_HEAD_MEMO VARCHAR2(100 BYTE) 
, MRKT_HEAD_DATE DATE 
, BATCH_ID NUMBER 
, CONSTRAINT INVOICE_REQUISITION_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.INVOICE_REQUISITION_PK ON OM.INVOICE_REQUISITION (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'LOV'
CREATE TABLE OM.LOV 
(
  ID NUMBER NOT NULL 
, LOOKUP_CODE VARCHAR2(100 BYTE) NOT NULL 
, LOOKUP_VALUE VARCHAR2(200 BYTE) NOT NULL 
, CONSTRAINT LOV_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.LOV_PK ON OM.LOV (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'PAYMENT'
CREATE TABLE OM.PAYMENT 
(
  ID NUMBER NOT NULL 
, INVOICE_ID NUMBER 
, PAYMENT_AMOUNT NUMBER 
, PAYMENT_DATE DATE 
, CREATED_BY VARCHAR2(20 BYTE) 
, CREATION_DATE DATE 
, MEMO VARCHAR2(200 BYTE) 
, CONSTRAINT PAYMENT_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.PAYMENT_PK ON OM.PAYMENT (ID ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create table 'USERS'
CREATE TABLE OM.USERS 
(
  USERNAME VARCHAR2(20 BYTE) NOT NULL 
, PASSWORD VARCHAR2(20 BYTE) NOT NULL 
, FIRSTNAME VARCHAR2(50 BYTE) 
, LASTNAME VARCHAR2(50 BYTE) 
, U_DESCRIPTION VARCHAR2(200 BYTE) 
, DEPARTMENT VARCHAR2(20 BYTE) 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USERNAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX OM.USERS_PK ON OM.USERS (USERNAME ASC) 
      LOGGING 
      TABLESPACE "SYSTEM" 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'APPROVAL_IN_PROCESS_PK'
CREATE UNIQUE INDEX OM.APPROVAL_IN_PROCESS_PK ON OM.APPROVAL_IN_PROCESS (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'APPROVAL_ROUTING_PK'
CREATE UNIQUE INDEX OM.APPROVAL_ROUTING_PK ON OM.APPROVAL_ROUTING (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'CHANGE_HISTORY_PK'
CREATE UNIQUE INDEX OM.CHANGE_HISTORY_PK ON OM.CHANGE_HISTORY (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'CONTRACT_ATTACHMENT_PK'
CREATE UNIQUE INDEX OM.CONTRACT_ATTACHMENT_PK ON OM.CONTRACT_ATTACHMENT (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'CONTRACT_LINE_PAYMENTS_PK'
CREATE UNIQUE INDEX OM.CONTRACT_LINE_PAYMENTS_PK ON OM.CONTRACT_LINE_PAYMENTS (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'CONTRACT_LINE_PK'
CREATE UNIQUE INDEX OM.CONTRACT_LINE_PK ON OM.CONTRACT_LINE (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'CONTRACT_PK'
CREATE UNIQUE INDEX OM.CONTRACT_PK ON OM.CONTRACT (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'CUSTOMER_CONTACTS_PK'
CREATE UNIQUE INDEX OM.CUSTOMER_CONTACTS_PK ON OM.CUSTOMER_CONTACTS (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'CUSTOMER_PK'
CREATE UNIQUE INDEX OM.CUSTOMER_PK ON OM.CUSTOMER (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'GROUPMEMBERS_PK'
CREATE UNIQUE INDEX OM.GROUPMEMBERS_PK ON OM.GROUPMEMBERS (G_NAME ASC, G_MEMBER ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'GROUPS_PK'
CREATE UNIQUE INDEX OM.GROUPS_PK ON OM.GROUPS (G_NAME ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'INVOICE_BATCH_PK'
CREATE UNIQUE INDEX OM.INVOICE_BATCH_PK ON OM.INVOICE_BATCH (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'INVOICE_REQUISITION_PK'
CREATE UNIQUE INDEX OM.INVOICE_REQUISITION_PK ON OM.INVOICE_REQUISITION (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'LOV_PK'
CREATE UNIQUE INDEX OM.LOV_PK ON OM.LOV (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'PAYMENT_PK'
CREATE UNIQUE INDEX OM.PAYMENT_PK ON OM.PAYMENT (ID ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT create index 'USERS_PK'
CREATE UNIQUE INDEX OM.USERS_PK ON OM.USERS (USERNAME ASC) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

PROMPT alter table 'CONTRACT'
ALTER TABLE OM.CONTRACT
ADD CONSTRAINT CONTRACT_CONTRACT_FK1 FOREIGN KEY
(
  PARENT_CONTRACT_ID 
)
REFERENCES OM.CONTRACT
(
  ID 
)
ENABLE;

PROMPT alter table 'CONTRACT'
ALTER TABLE OM.CONTRACT
ADD CONSTRAINT CONTRACT_CUSTOMER_CONTACT_FK1 FOREIGN KEY
(
  CUSTOMER_CONTACTOR 
)
REFERENCES OM.CUSTOMER_CONTACTS
(
  ID 
)
ENABLE;

PROMPT alter table 'CONTRACT_ATTACHMENT'
ALTER TABLE OM.CONTRACT_ATTACHMENT
ADD CONSTRAINT CONTRACT_ATTACHMENT_CONTR_FK1 FOREIGN KEY
(
  CONTRACT_ID 
)
REFERENCES OM.CONTRACT
(
  ID 
)
ENABLE;

PROMPT alter table 'CONTRACT_LINE'
ALTER TABLE OM.CONTRACT_LINE
ADD CONSTRAINT CONTRACT_LINE_CONTRACT_FK1 FOREIGN KEY
(
  HEADER_ID 
)
REFERENCES OM.CONTRACT
(
  ID 
)
ON DELETE CASCADE ENABLE;

PROMPT alter table 'CONTRACT_LINE_PAYMENTS'
ALTER TABLE OM.CONTRACT_LINE_PAYMENTS
ADD CONSTRAINT BATCH_INVOICE_FK1 FOREIGN KEY
(
  INVOICE_BATCH_ID 
)
REFERENCES OM.INVOICE_BATCH
(
  ID 
)
ENABLE;

PROMPT alter table 'CONTRACT_LINE_PAYMENTS'
ALTER TABLE OM.CONTRACT_LINE_PAYMENTS
ADD CONSTRAINT CONTRACT_LINE_PAYMENTS_CO_FK1 FOREIGN KEY
(
  LINE_ID 
)
REFERENCES OM.CONTRACT_LINE
(
  ID 
)
ON DELETE CASCADE ENABLE;

PROMPT alter table 'CUSTOMER_CONTACTS'
ALTER TABLE OM.CUSTOMER_CONTACTS
ADD CONSTRAINT CUSTOMER_CONTACTS_CUSTOME_FK1 FOREIGN KEY
(
  CUSOMTER_ID 
)
REFERENCES OM.CUSTOMER
(
  ID 
)
ENABLE;

PROMPT alter table 'GROUPMEMBERS'
ALTER TABLE OM.GROUPMEMBERS
ADD CONSTRAINT GROUPMEMBERS_GROUPS_FK1 FOREIGN KEY
(
  G_NAME 
)
REFERENCES OM.GROUPS
(
  G_NAME 
)
ENABLE;

PROMPT alter table 'GROUPMEMBERS'
ALTER TABLE OM.GROUPMEMBERS
ADD CONSTRAINT GROUPMEMBERS_USERS_FK1 FOREIGN KEY
(
  G_MEMBER 
)
REFERENCES OM.USERS
(
  USERNAME 
)
ENABLE;

PROMPT alter table 'PAYMENT'
ALTER TABLE OM.PAYMENT
ADD CONSTRAINT PAYMENT_INVOICE_FK1 FOREIGN KEY
(
  INVOICE_ID 
)
REFERENCES OM.CONTRACT_LINE_PAYMENTS
(
  ID 
)
ENABLE;

COMMENT ON COLUMN OM.CONTRACT.REFINED_FLAG IS '如果合同文本已经被处理过则为''Y''，反之为''N''';

PROMPT create sequence 'APPROVAL_SEQ'
CREATE SEQUENCE OM.APPROVAL_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'ATTACHMENT_SEQ'
CREATE SEQUENCE OM.ATTACHMENT_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'CHANGE_HISTORY_SEQ'
CREATE SEQUENCE OM.CHANGE_HISTORY_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'CHANGE_SEQ'
CREATE SEQUENCE OM.CHANGE_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'CONTRACT_LINE_SEQ'
CREATE SEQUENCE OM.CONTRACT_LINE_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'CONTRACT_PAYMENT_SEQ'
CREATE SEQUENCE OM.CONTRACT_PAYMENT_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'CONTRACT_SEQ'
CREATE SEQUENCE OM.CONTRACT_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'CUSTOMER_SEQ'
CREATE SEQUENCE OM.CUSTOMER_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'CUST_CONTACTS_SEQ'
CREATE SEQUENCE OM.CUST_CONTACTS_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'INVOICE_BATCH_SEQ'
CREATE SEQUENCE OM.INVOICE_BATCH_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'INVOICE_SEQ'
CREATE SEQUENCE OM.INVOICE_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'LOV_SEQ'
CREATE SEQUENCE OM.LOV_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'PAYMENT_SEQ'
CREATE SEQUENCE OM.PAYMENT_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

PROMPT create sequence 'ROUTING_SEQ'
CREATE SEQUENCE OM.ROUTING_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

SPOOL OFF