package com.xy.scpms.model.reports;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 09:17:58 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ARAgingReportRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DesignDept {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getDesignDept();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setDesignDept((String)value);
            }
        }
        ,
        IntactTotal {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getIntactTotal();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setIntactTotal((Number)value);
            }
        }
        ,
        FrozenTotal {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getFrozenTotal();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setFrozenTotal((Number)value);
            }
        }
        ,
        InvTotal {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getInvTotal();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setInvTotal((Number)value);
            }
        }
        ,
        PayTotal {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getPayTotal();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setPayTotal((Number)value);
            }
        }
        ,
        ArTotal {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getArTotal();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setArTotal((Number)value);
            }
        }
        ,
        Inv90 {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getInv90();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setInv90((Number)value);
            }
        }
        ,
        Inv180 {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getInv180();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setInv180((Number)value);
            }
        }
        ,
        Inv365 {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getInv365();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setInv365((Number)value);
            }
        }
        ,
        Inv730 {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getInv730();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setInv730((Number)value);
            }
        }
        ,
        Inv1095 {
            public Object get(ARAgingReportRowImpl obj) {
                return obj.getInv1095();
            }

            public void put(ARAgingReportRowImpl obj, Object value) {
                obj.setInv1095((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ARAgingReportRowImpl object);

        public abstract void put(ARAgingReportRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int DESIGNDEPT = AttributesEnum.DesignDept.index();
    public static final int INTACTTOTAL = AttributesEnum.IntactTotal.index();
    public static final int FROZENTOTAL = AttributesEnum.FrozenTotal.index();
    public static final int INVTOTAL = AttributesEnum.InvTotal.index();
    public static final int PAYTOTAL = AttributesEnum.PayTotal.index();
    public static final int ARTOTAL = AttributesEnum.ArTotal.index();
    public static final int INV90 = AttributesEnum.Inv90.index();
    public static final int INV180 = AttributesEnum.Inv180.index();
    public static final int INV365 = AttributesEnum.Inv365.index();
    public static final int INV730 = AttributesEnum.Inv730.index();
    public static final int INV1095 = AttributesEnum.Inv1095.index();
    

    /**
     * This is the default constructor (do not remove).
     */
    public ARAgingReportRowImpl() {
    }
    
  

    /**
     * Gets the attribute value for the calculated attribute DesignDept.
     * @return the DesignDept
     */
    public String getDesignDept() {
        return (String) getAttributeInternal(DESIGNDEPT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DesignDept.
     * @param value value to set the  DesignDept
     */
    public void setDesignDept(String value) {
        setAttributeInternal(DESIGNDEPT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IntactTotal.
     * @return the IntactTotal
     */
    public Number getIntactTotal() {
        return (Number) getAttributeInternal(INTACTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IntactTotal.
     * @param value value to set the  IntactTotal
     */
    public void setIntactTotal(Number value) {
        setAttributeInternal(INTACTTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FrozenTotal.
     * @return the FrozenTotal
     */
    public Number getFrozenTotal() {
        return (Number) getAttributeInternal(FROZENTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FrozenTotal.
     * @param value value to set the  FrozenTotal
     */
    public void setFrozenTotal(Number value) {
        setAttributeInternal(FROZENTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvTotal.
     * @return the InvTotal
     */
    public Number getInvTotal() {
        return (Number) getAttributeInternal(INVTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvTotal.
     * @param value value to set the  InvTotal
     */
    public void setInvTotal(Number value) {
        setAttributeInternal(INVTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PayTotal.
     * @return the PayTotal
     */
    public Number getPayTotal() {
        return (Number) getAttributeInternal(PAYTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PayTotal.
     * @param value value to set the  PayTotal
     */
    public void setPayTotal(Number value) {
        setAttributeInternal(PAYTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ArTotal.
     * @return the ArTotal
     */
    public Number getArTotal() {
        return (Number) getAttributeInternal(ARTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ArTotal.
     * @param value value to set the  ArTotal
     */
    public void setArTotal(Number value) {
        setAttributeInternal(ARTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inv90.
     * @return the Inv90
     */
    public Number getInv90() {
        return (Number) getAttributeInternal(INV90);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inv90.
     * @param value value to set the  Inv90
     */
    public void setInv90(Number value) {
        setAttributeInternal(INV90, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inv180.
     * @return the Inv180
     */
    public Number getInv180() {
        return (Number) getAttributeInternal(INV180);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inv180.
     * @param value value to set the  Inv180
     */
    public void setInv180(Number value) {
        setAttributeInternal(INV180, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inv365.
     * @return the Inv365
     */
    public Number getInv365() {
        return (Number) getAttributeInternal(INV365);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inv365.
     * @param value value to set the  Inv365
     */
    public void setInv365(Number value) {
        setAttributeInternal(INV365, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inv730.
     * @return the Inv730
     */
    public Number getInv730() {
        return (Number) getAttributeInternal(INV730);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inv730.
     * @param value value to set the  Inv730
     */
    public void setInv730(Number value) {
        setAttributeInternal(INV730, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Inv1095.
     * @return the Inv1095
     */
    public Number getInv1095() {
        return (Number) getAttributeInternal(INV1095);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Inv1095.
     * @param value value to set the  Inv1095
     */
    public void setInv1095(Number value) {
        setAttributeInternal(INV1095, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
