package com.xy.scpms.model.reports;

import com.xy.scpms.model.common.NoAutoQueryView;

import com.xy.scpms.model.reports.common.AuthorizerTypePerfRpt;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 07 13:05:31 CST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AuthorizerTypePerfRptImpl extends NoAutoQueryView implements AuthorizerTypePerfRpt {
    /**
     * This is the default constructor (do not remove).
     */
    public AuthorizerTypePerfRptImpl() {
    }
    
    public void doQuery(Date start,Date end){
        
             
        if(start!=null)
            this.setstartdate(start);
        if(end!=null)
            this.setendDate(end);
        
        this.executeQuery();
    }

    /**
     * Returns the bind variable value for startdate.
     * @return bind variable value for startdate
     */
    public Date getstartdate() {
        return (Date)getNamedWhereClauseParam("startdate");
    }

    /**
     * Sets <code>value</code> for bind variable startdate.
     * @param value value to bind as startdate
     */
    public void setstartdate(Date value) {
        setNamedWhereClauseParam("startdate", value);
    }

    /**
     * Returns the bind variable value for endDate.
     * @return bind variable value for endDate
     */
    public Date getendDate() {
        return (Date)getNamedWhereClauseParam("endDate");
    }

    /**
     * Sets <code>value</code> for bind variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(Date value) {
        setNamedWhereClauseParam("endDate", value);
    }
}
