package com.xy.scpms.model.reports;


import com.xy.scpms.model.reports.common.UrgeSettlementRpt;

import java.util.ArrayList;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaItem;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 27 09:02:10 CST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UrgeSettlementRptImpl extends ViewObjectImpl implements UrgeSettlementRpt {
    /**
     * This is the default constructor (do not remove).
     */
    public UrgeSettlementRptImpl() {
    }

    public void queryByContractNos(ArrayList contractNos) {

        ViewCriteria vc = this.createViewCriteria();
        ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
        ViewCriteriaItem vcRowItem = vcRow.ensureCriteriaItem("ContractNo");
        vcRowItem.setOperator("IN");
        int i =0;
        for(Object contractNo:contractNos){            
            
            vcRowItem.setValue(i++,contractNo);
        }       
        vc.addElement(vcRow);
        this.applyViewCriteria(vc);
        
        this.executeQuery();

    }
}
