package edu.hp.model.biz.client;

import edu.hp.model.biz.common.HomeModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 07 13:51:43 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HomeModuleClient extends ApplicationModuleImpl implements HomeModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HomeModuleClient() {
    }

    public void initDashboard(String userName) {
        Object _ret = this.riInvokeExportedMethod(this,"initDashboard",new String [] {"java.lang.String"},new Object[] {userName});
        return;
    }
}
