package edu.hp.model.biz.client;

import edu.hp.model.biz.common.PurchaseOrderAppModule;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 07 21:12:40 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PurchaseOrderAppModuleClient extends ApplicationModuleImpl implements PurchaseOrderAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public PurchaseOrderAppModuleClient() {
    }

    public void findByPoId(String poId) {
        Object _ret = this.riInvokeExportedMethod(this,"findByPoId",new String [] {"java.lang.String"},new Object[] {poId});
        return;
    }

    public void findByUserId(String submitterId) {
        Object _ret = this.riInvokeExportedMethod(this,"findByUserId",new String [] {"java.lang.String"},new Object[] {submitterId});
        return;
    }

    public BigDecimal getApprovalLimitForCategoryId(String categoryId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getApprovalLimitForCategoryId",new String [] {"java.lang.String"},new Object[] {categoryId});
        return (BigDecimal)_ret;
    }

    public void newPo(String userId) {
        Object _ret = this.riInvokeExportedMethod(this,"newPo",new String [] {"java.lang.String"},new Object[] {userId});
        return;
    }
}
