package edu.hp.model.vo.query.home;

import edu.hp.model.common.Constants;
import edu.hp.model.vo.query.home.common.UserTasks;

import oracle.jbo.server.ViewObjectImpl;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 07 13:49:05 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserTasksImpl extends ViewObjectImpl implements UserTasks {
    /**
     * This is the default constructor (do not remove).
     */
    public UserTasksImpl() {
    }
    
    public void setForPending(){
        this.setApplyViewCriteriaNames(null);
        this.applyViewCriteria(getViewCriteria("findByState"));
        this.setstate(Constants.STATE_TASK_PENDING);
        this.executeQuery();
    }
    public void setForCompleted(){
        this.setApplyViewCriteriaNames(null);
        this.applyViewCriteria(getViewCriteria("findByState"));
        this.setstate(Constants.STATE_TASK_COMPLETED);
        this.executeQuery();
    }
    
    public void setForAll(){
        this.setApplyViewCriteriaNames(null);       
        this.executeQuery();
    }

    /**
     * Returns the bind variable value for userName.
     * @return bind variable value for userName
     */
    public String getuserName() {
        return (String)getNamedWhereClauseParam("userName");
    }

    /**
     * Sets <code>value</code> for bind variable userName.
     * @param value value to bind as userName
     */
    public void setuserName(String value) {
        setNamedWhereClauseParam("userName", value);
    }

    /**
     * Returns the variable value for state.
     * @return variable value for state
     */
    public String getstate() {
        return (String)ensureVariableManager().getVariableValue("state");
    }

    /**
     * Sets <code>value</code> for variable state.
     * @param value value to bind as state
     */
    public void setstate(String value) {
        ensureVariableManager().setVariableValue("state", value);
    }
}
