package edu.hp.model.vo.query.helpdesk.client;

import edu.hp.model.vo.query.helpdesk.common.ReasonLevel2WithEmpty;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 15 20:53:58 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReasonLevel2WithEmptyClient extends ViewUsageImpl implements ReasonLevel2WithEmpty {
    /**
     * This is the default constructor (do not remove).
     */
    public ReasonLevel2WithEmptyClient() {
    }

    public void setparentCode(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setparentCode",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
