package edu.hp.model.vo;

import edu.hp.model.vo.common.DocumentTaskView;

import oracle.jbo.Variable;
import oracle.jbo.ViewCriteria;
import oracle.jbo.common.VariableImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 20:52:11 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentTaskViewImpl extends ViewObjectImpl implements DocumentTaskView {
    /**
     * This is the default constructor (do not remove).
     */
    public DocumentTaskViewImpl() {
    }

    public void search(String taskName, String state, Date startDate, Date endDate) {
        System.err.println(taskName);
        System.err.println(state);
        System.err.println(startDate);
        System.err.println(endDate);
        
        this.setApplyViewCriteriaNames(null);
        ViewCriteria criteria = this.getViewCriteria("mainSearch");
        this.setRangeSize(-1);
        this.applyViewCriteria(criteria);
        this.settaskName(taskName);
        this.setstate(state);
        this.setstartDate(startDate);
        this.setendDate(endDate);
        this.executeQuery();

//        VariableImpl taskNameVar = new VariableImpl();
//        taskNameVar.setName("taskName");
//        VariableImpl stateVar = new VariableImpl();
//        stateVar.setName("state");
//        VariableImpl startDateVar = new VariableImpl();
//        startDateVar.setName("startDate");
//        VariableImpl endDateVar = new VariableImpl();
//        endDateVar.setName("endDate");
//        this.findByViewCriteriaWithBindVars(this.getViewCriteria("mainSearch"), -1,
//                                            this.QUERY_MODE_SCAN_DATABASE_TABLES,
//                                            new Variable[] { taskNameVar, stateVar, startDateVar, endDateVar },
//                                            new Object[] { taskName, state, startDate, endDate });
    }

    /**
     * Returns the variable value for startDate.
     * @return variable value for startDate
     */
    public Date getstartDate() {
        return (Date)ensureVariableManager().getVariableValue("startDate");
    }

    /**
     * Sets <code>value</code> for variable startDate.
     * @param value value to bind as startDate
     */
    public void setstartDate(Date value) {
        ensureVariableManager().setVariableValue("startDate", value);
    }

    /**
     * Returns the variable value for endDate.
     * @return variable value for endDate
     */
    public Date getendDate() {
        return (Date)ensureVariableManager().getVariableValue("endDate");
    }

    /**
     * Sets <code>value</code> for variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(Date value) {
        ensureVariableManager().setVariableValue("endDate", value);
    }

    /**
     * Returns the variable value for state.
     * @return variable value for state
     */
    public String getstate() {
        return (String)ensureVariableManager().getVariableValue("state");
    }

    /**
     * Sets <code>value</code> for variable state.
     * @param value value to bind as state
     */
    public void setstate(String value) {
        ensureVariableManager().setVariableValue("state", value);
    }

    /**
     * Returns the variable value for taskName.
     * @return variable value for taskName
     */
    public String gettaskName() {
        return (String)ensureVariableManager().getVariableValue("taskName");
    }

    /**
     * Sets <code>value</code> for variable taskName.
     * @param value value to bind as taskName
     */
    public void settaskName(String value) {
        ensureVariableManager().setVariableValue("taskName", value);
    }
}
