package edu.hp.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 24 20:35:06 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemCategoryApprovalViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ItemCategoryApprovalViewImpl() {
    }


    /**
     * Returns the variable value for CategoryId.
     * @return variable value for CategoryId
     */
    public String getCategoryId() {
        return (String)ensureVariableManager().getVariableValue("CategoryId");
    }

    /**
     * Sets <code>value</code> for variable CategoryId.
     * @param value value to bind as CategoryId
     */
    public void setCategoryId(String value) {
        ensureVariableManager().setVariableValue("CategoryId", value);
    }
}
