package edu.hp.model.vo;

import edu.hp.model.vo.common.PurchaseOrderLinesView;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 08 21:07:23 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PurchaseOrderLinesViewImpl extends ViewObjectImpl implements PurchaseOrderLinesView {
    /**
     * This is the default constructor (do not remove).
     */
    public PurchaseOrderLinesViewImpl() {
    }
    
    public void newRow() {
        System.out.println("In PoLineVO. To create new line");
        Row newRow = this.createRow();
        newRow.setAttribute("State", "1");
        this.insertRow(newRow);        
        this.setCurrentRow(newRow);
    }
}
