package edu.hp.model.vo;

import edu.hp.model.vo.common.RoleUsersView;

import oracle.jbo.Row;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 13 12:07:42 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RoleUsersViewImpl extends ViewObjectImpl implements RoleUsersView {
    /**
     * This is the default constructor (do not remove).
     */
    public RoleUsersViewImpl() {
    }
    
    public boolean isUserInRole(String userId, String roleName) {
        this.setApplyViewCriteriaNames(null);
        
        this.setUserBV(userId);
        this.setRoleBV(roleName);
        
        ViewCriteria vc = this.getViewCriteria("RoleUserIdCriteria");
        this.setApplyViewCriteriaName(vc.getName());
        this.executeQuery();
        
        Row[] rows = this.getAllRowsInRange();
        if (rows != null && rows.length > 0) {
            return true;
        } 
        return false;
    }

    /**
     * Returns the variable value for UserBV.
     * @return variable value for UserBV
     */
    public String getUserBV() {
        return (String)ensureVariableManager().getVariableValue("UserBV");
    }

    /**
     * Sets <code>value</code> for variable UserBV.
     * @param value value to bind as UserBV
     */
    public void setUserBV(String value) {
        ensureVariableManager().setVariableValue("UserBV", value);
    }

    /**
     * Returns the variable value for RoleBV.
     * @return variable value for RoleBV
     */
    public String getRoleBV() {
        return (String)ensureVariableManager().getVariableValue("RoleBV");
    }

    /**
     * Sets <code>value</code> for variable RoleBV.
     * @param value value to bind as RoleBV
     */
    public void setRoleBV(String value) {
        ensureVariableManager().setVariableValue("RoleBV", value);
    }
}
