package edu.hp.model.vo.query.security;

import edu.hp.model.vo.query.security.common.UserMenuQuery;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 13 16:37:18 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserMenuQueryImpl extends ViewObjectImpl implements UserMenuQuery {
    /**
     * This is the default constructor (do not remove).
     */
    public UserMenuQueryImpl() {
    }
    
    /**
     * 执行查询，需要以下三个条件 Gene
     * @param masterCategory
     * @param category
     * @param userName
     */
    public void queryUserMenu(String masterCategory, String category, String userName){        
        this.setApplyViewCriteriaNames(null);
        ViewCriteria criteria = this.getViewCriteria("QueryByCategory");
        this.applyViewCriteria(criteria);
        this.setmasterCategory(masterCategory);
        this.setcategory(category);
        this.setuserName(userName);
        this.executeQuery();
    }
    
    public void queryUserMenu(String userName){
        
        this.setApplyViewCriteriaNames(null);
        this.setuserName(userName);
        this.executeQuery();
    }

    /**
     * Returns the bind variable value for userName.
     * @return bind variable value for userName
     */
    public String getuserName() {
        return (String)getNamedWhereClauseParam("userName");
    }

    /**
     * Sets <code>value</code> for bind variable userName.
     * @param value value to bind as userName
     */
    public void setuserName(String value) {
        setNamedWhereClauseParam("userName", value);
    }

    /**
     * Returns the variable value for category.
     * @return variable value for category
     */
    public String getcategory() {
        return (String)ensureVariableManager().getVariableValue("category");
    }

    /**
     * Sets <code>value</code> for variable category.
     * @param value value to bind as category
     */
    public void setcategory(String value) {
        ensureVariableManager().setVariableValue("category", value);
    }

    /**
     * Returns the variable value for masterCategory.
     * @return variable value for masterCategory
     */
    public String getmasterCategory() {
        return (String)ensureVariableManager().getVariableValue("masterCategory");
    }

    /**
     * Sets <code>value</code> for variable masterCategory.
     * @param value value to bind as masterCategory
     */
    public void setmasterCategory(String value) {
        ensureVariableManager().setVariableValue("masterCategory", value);
    }
}
