package edu.hp.model.vo.query.security;

import edu.hp.model.vo.query.security.common.UserGroupQuery;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 16 11:38:17 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserGroupQueryImpl extends ViewObjectImpl implements UserGroupQuery {
    /**
     * This is the default constructor (do not remove).
     */
    public UserGroupQueryImpl() {
    }
    
    public void query(String grpName){
        this.setgrpName(grpName);
        this.setRangeSize(-1);
        this.executeQuery();
    }


    /**
     * Returns the bind variable value for grpName.
     * @return bind variable value for grpName
     */
    public String getgrpName() {
        return (String)getNamedWhereClauseParam("grpName");
    }

    /**
     * Sets <code>value</code> for bind variable grpName.
     * @param value value to bind as grpName
     */
    public void setgrpName(String value) {
        setNamedWhereClauseParam("grpName", value);
    }
}
