package edu.hp.model.vo.query.security.client;

import edu.hp.model.vo.query.security.common.UserMenuQuery;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 13 16:40:17 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UserMenuQueryClient extends ViewUsageImpl implements UserMenuQuery {
    /**
     * This is the default constructor (do not remove).
     */
    public UserMenuQueryClient() {
    }

    public void queryUserMenu(String userName) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"queryUserMenu",new String [] {"java.lang.String"},new Object[] {userName});
        return;
    }

    public void queryUserMenu(String masterCategory, String category, String userName) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"queryUserMenu",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {masterCategory, category, userName});
        return;
    }
}
