package com.xy.scpms.model.vo;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 05 13:30:05 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FourTechSeqViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FourTechSeqViewImpl() {
    }
    
    /**
     * Returns the variable value for year.
     * @return variable value for year
     */
    public Number getyear() {
        return (Number)ensureVariableManager().getVariableValue("year");
    }

    /**
     * Sets <code>value</code> for variable year.
     * @param value value to bind as year
     */
    public void setyear(Number value) {
        ensureVariableManager().setVariableValue("year", value);
    }

    /**
     * Returns the variable value for type.
     * @return variable value for type
     */
    public String gettype() {
        return (String)ensureVariableManager().getVariableValue("type");
    }

    /**
     * Sets <code>value</code> for variable type.
     * @param value value to bind as type
     */
    public void settype(String value) {
        ensureVariableManager().setVariableValue("type", value);
    }
}
