package com.xy.scpms.model.reports;

import com.xy.scpms.model.common.NoAutoQueryView;
import com.xy.scpms.model.reports.common.DynamicPaymentStatusByYear;

import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 30 21:46:20 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DynamicPaymentStatusByYearImpl extends NoAutoQueryView implements DynamicPaymentStatusByYear {
    /**
     * This is the default constructor (do not remove).
     */
    public DynamicPaymentStatusByYearImpl() {
    }
    
    public void applyDeptCriteria(){
        this.setApplyViewCriteriaNames(null);
        ViewCriteria criteria = this.getViewCriteria("byDept");
        this.setApplyViewCriteriaNames(null);
        this.applyViewCriteria(criteria);
    }

    /**
     * Returns the bind variable value for yearBind.
     * @return bind variable value for yearBind
     */
    public Number getyearBind() {
        return (Number)getNamedWhereClauseParam("yearBind");
    }

    /**
     * Sets <code>value</code> for bind variable yearBind.
     * @param value value to bind as yearBind
     */
    public void setyearBind(Number value) {
        setNamedWhereClauseParam("yearBind", value);
    }

    /**
     * Returns the variable value for dept.
     * @return variable value for dept
     */
    public String getdept() {
        return (String)ensureVariableManager().getVariableValue("dept");
    }

    /**
     * Sets <code>value</code> for variable dept.
     * @param value value to bind as dept
     */
    public void setdept(String value) {
        ensureVariableManager().setVariableValue("dept", value);
    }
}
