package com.xy.scpms.model.reports;


import com.xy.scpms.model.reports.common.InvoicedNotPaid;


import java.sql.SQLException;

import java.util.ArrayList;

import oracle.jbo.domain.Array;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 27 09:43:33 CST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoicedNotPaidImpl extends ViewObjectImpl implements InvoicedNotPaid {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoicedNotPaidImpl() {
    }

    public void runQuery(ArrayList contractNos) {
//        this.setWhereClause(null);
//        this.setWhereClauseParams(null);
//        StringBuffer inClause = new StringBuffer();
//        inClause.append("(");
//        int i = 1;
//        for (Object contract : contractNos) {
//            inClause.append("'");
//            inClause.append(contract);
//            inClause.append("'");
//            if (i++ < contractNos.size())
//                inClause.append(",");
//        }
//        inClause.append(")");
//        System.err.println(inClause.toString());
        Array contractNosArray;

        try {
            contractNosArray = new Array(contractNos);
            this.setcontractNos(contractNosArray);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
//        System.out.println(this.getQuery());
        this.executeQuery();
       
        

    }


    /**
     * Returns the bind variable value for contractNos.
     * @return bind variable value for contractNos
     */
    public Array getcontractNos() {
        return (Array)getNamedWhereClauseParam("contractNos");
    }

    /**
     * Sets <code>value</code> for bind variable contractNos.
     * @param value value to bind as contractNos
     */
    public void setcontractNos(Array value) {
        setNamedWhereClauseParam("contractNos", value);
    }
}
