package edu.hp.model.vo.report.meal;

import edu.hp.model.vo.report.meal.common.MealReport;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 02 14:40:07 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MealReportImpl extends ViewObjectImpl implements MealReport {
    /**
     * This is the default constructor (do not remove).
     */
    public MealReportImpl() {
    }
    
    public void runReport(String location, Date startDt, Date endDt){
        this.setRangeSize(-1);
        if(location.equals("ZZ")) location = "自忠";
        else if(location.equals("LY")) location = "丽园";
        else location = null;
        this.setloc(location);
        this.setml_st(startDt);
        this.setml_ed(endDt);
        this.executeQuery();
    }

    /**
     * Returns the bind variable value for loc.
     * @return bind variable value for loc
     */
    public String getloc() {
        return (String)getNamedWhereClauseParam("loc");
    }

    /**
     * Sets <code>value</code> for bind variable loc.
     * @param value value to bind as loc
     */
    public void setloc(String value) {
        setNamedWhereClauseParam("loc", value);
    }

    /**
     * Returns the bind variable value for ml_ed.
     * @return bind variable value for ml_ed
     */
    public Date getml_ed() {
        return (Date)getNamedWhereClauseParam("ml_ed");
    }

    /**
     * Sets <code>value</code> for bind variable ml_ed.
     * @param value value to bind as ml_ed
     */
    public void setml_ed(Date value) {
        setNamedWhereClauseParam("ml_ed", value);
    }

    /**
     * Returns the bind variable value for ml_st.
     * @return bind variable value for ml_st
     */
    public Date getml_st() {
        return (Date)getNamedWhereClauseParam("ml_st");
    }

    /**
     * Sets <code>value</code> for bind variable ml_st.
     * @param value value to bind as ml_st
     */
    public void setml_st(Date value) {
        setNamedWhereClauseParam("ml_st", value);
    }
}
