package edu.hp.model.vo.client;

import edu.hp.model.vo.common.ClassroomCalendarView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 19 14:03:36 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClassroomCalendarViewClient extends ViewUsageImpl implements ClassroomCalendarView {
    /**
     * This is the default constructor (do not remove).
     */
    public ClassroomCalendarViewClient() {
    }


    public void newRow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"newRow",null,null);
        return;
    }

    public void refreshCalendar(String clsRmNos) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"refreshCalendar",new String [] {"java.lang.String"},new Object[] {clsRmNos});
        return;
    }

    public void removeRow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"removeRow",null,null);
        return;
    }

    public void setclsRmNos(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setclsRmNos",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }
}
