package edu.hp.model.vo.client;

import edu.hp.model.vo.common.ClsRmCalDMLView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 20 13:24:04 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ClsRmCalDMLViewClient extends ViewUsageImpl implements ClsRmCalDMLView {
    /**
     * This is the default constructor (do not remove).
     */
    public ClsRmCalDMLViewClient() {
    }


    public void deleteByPK(String clsRmCalId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"deleteByPK",new String [] {"java.lang.String"},new Object[] {clsRmCalId});
        return;
    }

    public void newRow(String userDisplayName, String userId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"newRow",new String [] {"java.lang.String","java.lang.String"},new Object[] {userDisplayName, userId});
        return;
    }

    public void queryByPK(String clsRmCalId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"queryByPK",new String [] {"java.lang.String"},new Object[] {clsRmCalId});
        return;
    }
}
