package edu.hp.model.vo.client;

import edu.hp.model.vo.common.DocumentTaskView;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 21:03:34 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DocumentTaskViewClient extends ViewUsageImpl implements DocumentTaskView {
    /**
     * This is the default constructor (do not remove).
     */
    public DocumentTaskViewClient() {
    }

    public void search(String taskName, String state, Date startDate, Date endDate) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"search",new String [] {"java.lang.String","java.lang.String","oracle.jbo.domain.Date","oracle.jbo.domain.Date"},new Object[] {taskName, state, startDate, endDate});
        return;
    }
}
