package edu.hp.model.vo.client;

import edu.hp.model.vo.common.HelpdeskCallsView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 26 21:28:06 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HelpdeskCallsViewClient extends ViewUsageImpl implements HelpdeskCallsView {
    /**
     * This is the default constructor (do not remove).
     */
    public HelpdeskCallsViewClient() {
    }

    public void doQuery(String level) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"doQuery",new String [] {"java.lang.String"},new Object[] {level});
        return;
    }
}
