package edu.hp.model.vo.client;

import edu.hp.model.vo.common.PurchaseOrderLinesView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 08 21:08:30 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PurchaseOrderLinesViewClient extends ViewUsageImpl implements PurchaseOrderLinesView {
    /**
     * This is the default constructor (do not remove).
     */
    public PurchaseOrderLinesViewClient() {
    }

    public void newRow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"newRow",null,null);
        return;
    }
}
