package com.xy.scpms.model.reports.client;

import com.xy.scpms.model.reports.common.EVEReport;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 08 20:49:16 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EVEReportClient extends ViewUsageImpl implements EVEReport {
    /**
     * This is the default constructor (do not remove).
     */
    public EVEReportClient() {
    }

    public void clearRowSet() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"clearRowSet",null,null);
        return;
    }

    public void runReportCriteria(oracle.jbo.domain.Number month,
                                  oracle.jbo.domain.Number year) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"runReportCriteria",new String [] {"oracle.jbo.domain.Number","oracle.jbo.domain.Number"},new Object[] {month, year});
        return;
    }
}
