package com.xy.scpms.model.reports.client;

import com.xy.scpms.model.reports.common.RegMgrPerfRpt;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 12 19:13:07 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegMgrPerfRptClient extends ViewUsageImpl implements RegMgrPerfRpt {
    /**
     * This is the default constructor (do not remove).
     */
    public RegMgrPerfRptClient() {
    }

    public void clearRowSet() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"clearRowSet",null,null);
        return;
    }

    public void doQuery(Date start, Date end, String mgrId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"doQuery",new String [] {"oracle.jbo.domain.Date","oracle.jbo.domain.Date","java.lang.String"},new Object[] {start, end, mgrId});
        return;
    }
}
