package edu.hp.model.vo.query.vehicle.client;

import edu.hp.model.vo.query.vehicle.common.VehicleCalQueryView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 31 13:06:51 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VehicleCalQueryViewClient extends ViewUsageImpl implements VehicleCalQueryView {
    /**
     * This is the default constructor (do not remove).
     */
    public VehicleCalQueryViewClient() {
    }


    public void findByDateRange() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"findByDateRange",null,null);
        return;
    }

    public void findByUserId(boolean enabled, String userId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"findByUserId",new String [] {"boolean","java.lang.String"},new Object[] {new Boolean(enabled), userId});
        return;
    }

    public void refreshCalendar(String vehicleIds) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"refreshCalendar",new String [] {"java.lang.String"},new Object[] {vehicleIds});
        return;
    }
}
