package com.xy.scpms.model.reports.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 01 21:18:54 CST 2011
// ---------------------------------------------------------------------
public interface ARAgingReport extends ViewObject {
    void runReportCriteria(oracle.jbo.domain.Number month,
                           oracle.jbo.domain.Number year);

    void clearRowSet();
}
