package com.xy.scpms.model.reports.client;

import com.xy.scpms.model.reports.common.DynamicPaymentStatusByYear;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 30 21:46:29 CST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DynamicPaymentStatusByYearClient extends ViewUsageImpl implements DynamicPaymentStatusByYear {
    /**
     * This is the default constructor (do not remove).
     */
    public DynamicPaymentStatusByYearClient() {
    }


    public void setyearBind(Integer value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setyearBind",new String [] {"java.lang.Integer"},new Object[] {value});
        return;
    }


    public void applyDeptCriteria() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"applyDeptCriteria",null,null);
        return;
    }

    public void clearRowSet() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"clearRowSet",null,null);
        return;
    }

    public void setdept(String value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setdept",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }

    public void setyearBind(oracle.jbo.domain.Number value) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setyearBind",new String [] {"oracle.jbo.domain.Number"},new Object[] {value});
        return;
    }
}
