package edu.hp.model.vo.query.admin;

import edu.hp.model.vo.query.admin.common.EmployeeQueryByDisplayNameView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 15 19:31:44 CST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeQueryByDisplayNameViewImpl extends ViewObjectImpl implements EmployeeQueryByDisplayNameView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeQueryByDisplayNameViewImpl() {
    }
    
    public void query(String userName){
        this.setdisplayName(userName);
        System.err.println(userName+"123");
        this.setRangeSize(-1);
        this.executeQuery();
        System.err.println(this.getAllRowsInRange().length);
    }

    /**
     * Returns the bind variable value for displayName.
     * @return bind variable value for displayName
     */
    public String getdisplayName() {
        return (String)getNamedWhereClauseParam("displayName");
    }

    /**
     * Sets <code>value</code> for bind variable displayName.
     * @param value value to bind as displayName
     */
    public void setdisplayName(String value) {
        setNamedWhereClauseParam("displayName", value);
    }
}
