package com.xy.scpms.model.reports.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 30 21:46:28 CST 2011
// ---------------------------------------------------------------------
public interface DynamicPaymentStatusByYear extends ViewObject {
    void setyearBind(Number value);

    void setdept(String value);

    void applyDeptCriteria();

    void clearRowSet();
}
