package com.xy.scpms.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 27 09:44:24 CST 2011
// ---------------------------------------------------------------------
public interface ContractLinePaymentsView extends ViewObject {
    void setCurrentRowById(oracle.jbo.domain.Number id);
}
