package com.xy.scpms.model.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 28 09:56:01 CST 2011
// ---------------------------------------------------------------------
public interface PaymentHistoryView extends ViewObject {
    String getdept();

    oracle.jbo.domain.Number getendYr();

    oracle.jbo.domain.Number getstartYr();

    void queryByYrDept(String dept, oracle.jbo.domain.Number start,
                       oracle.jbo.domain.Number end);

    void clearRowSet();
}
